CREATE TABLE IF NOT EXISTS `DBHouse` (
  `HouseNumber` int(11) NOT NULL DEFAULT '0',
  `X` int(11) NOT NULL DEFAULT '0',
  `Y` int(11) NOT NULL DEFAULT '0',
  `Z` int(11) NOT NULL DEFAULT '0',
  `RegionID` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Heading` int(11) NOT NULL DEFAULT '0',
  `CreationTime` datetime DEFAULT NULL,
  `Name` text,
  `Model` int(11) NOT NULL DEFAULT '0',
  `Emblem` int(11) NOT NULL DEFAULT '0',
  `PorchRoofColor` int(11) NOT NULL DEFAULT '0',
  `PorchMaterial` int(11) NOT NULL DEFAULT '0',
  `RoofMaterial` int(11) NOT NULL DEFAULT '0',
  `DoorMaterial` int(11) NOT NULL DEFAULT '0',
  `WallMaterial` int(11) NOT NULL DEFAULT '0',
  `TrussMaterial` int(11) NOT NULL DEFAULT '0',
  `WindowMaterial` int(11) NOT NULL DEFAULT '0',
  `Rug1Color` int(11) NOT NULL DEFAULT '0',
  `Rug2Color` int(11) NOT NULL DEFAULT '0',
  `Rug3Color` int(11) NOT NULL DEFAULT '0',
  `Rug4Color` int(11) NOT NULL DEFAULT '0',
  `IndoorGuildBanner` tinyint(1) NOT NULL DEFAULT '0',
  `IndoorGuildShield` tinyint(1) NOT NULL DEFAULT '0',
  `OutdoorGuildBanner` tinyint(1) NOT NULL DEFAULT '0',
  `OutdoorGuildShield` tinyint(1) NOT NULL DEFAULT '0',
  `Porch` tinyint(1) NOT NULL DEFAULT '0',
  `OwnerID` text,
  `LastPaid` datetime DEFAULT NULL,
  `KeptMoney` bigint(20) NOT NULL DEFAULT '0',
  `NoPurge` tinyint(1) NOT NULL DEFAULT '0',
  `GuildHouse` tinyint(1) NOT NULL DEFAULT '0',
  `GuildName` text,
  `HasConsignment` tinyint(1) NOT NULL DEFAULT '0',
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `DBHouse_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HouseNumber`),
  UNIQUE KEY `U_DBHouse_DBHouse_ID` (`DBHouse_ID`),
  KEY `I_DBHouse_RegionID` (`RegionID`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
