CREATE TABLE IF NOT EXISTS `Guild` (
  `GuildID` varchar(255) DEFAULT NULL,
  `GuildName` varchar(255) DEFAULT NULL,
  `Realm` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `GuildBanner` tinyint(1) NOT NULL DEFAULT '0',
  `GuildBannerLostTime` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Motd` text,
  `oMotd` text,
  `AllianceID` varchar(255) DEFAULT NULL,
  `Emblem` int(11) NOT NULL DEFAULT '0',
  `RealmPoints` bigint(20) NOT NULL DEFAULT '0',
  `BountyPoints` bigint(20) NOT NULL DEFAULT '0',
  `Webpage` text,
  `Email` text,
  `Dues` tinyint(1) NOT NULL DEFAULT '0',
  `Bank` double NOT NULL DEFAULT '0',
  `DuesPercent` bigint(20) NOT NULL DEFAULT '0',
  `HaveGuildHouse` tinyint(1) NOT NULL DEFAULT '0',
  `GuildHouseNumber` int(11) NOT NULL DEFAULT '0',
  `GuildLevel` bigint(20) NOT NULL DEFAULT '0',
  `BonusType` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `BonusStartTime` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `MeritPoints` bigint(20) NOT NULL DEFAULT '0',
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Guild_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`Guild_ID`),
  UNIQUE KEY `U_Guild_GuildID` (`GuildID`),
  KEY `I_Guild_GuildName` (`GuildName`),
  KEY `I_Guild_AllianceID` (`AllianceID`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
