DROP TABLE IF EXISTS `Spell`;

CREATE TABLE `Spell` (
  `SpellID` int(11) NOT NULL DEFAULT '0',
  `ClientEffect` int(11) NOT NULL DEFAULT '0',
  `Icon` int(11) NOT NULL DEFAULT '0',
  `Name` text NOT NULL,
  `Description` text NOT NULL,
  `Target` text NOT NULL,
  `Range` int(11) NOT NULL DEFAULT '0',
  `Power` int(11) NOT NULL DEFAULT '0',
  `CastTime` double NOT NULL DEFAULT '0',
  `Damage` double NOT NULL DEFAULT '0',
  `DamageType` int(11) NOT NULL DEFAULT '0',
  `Type` text,
  `Duration` int(11) NOT NULL DEFAULT '0',
  `Frequency` int(11) NOT NULL DEFAULT '0',
  `Pulse` int(11) NOT NULL DEFAULT '0',
  `PulsePower` int(11) NOT NULL DEFAULT '0',
  `Radius` int(11) NOT NULL DEFAULT '0',
  `RecastDelay` int(11) NOT NULL DEFAULT '0',
  `ResurrectHealth` int(11) NOT NULL DEFAULT '0',
  `ResurrectMana` int(11) NOT NULL DEFAULT '0',
  `Value` double NOT NULL DEFAULT '0',
  `Concentration` int(11) NOT NULL DEFAULT '0',
  `LifeDrainReturn` int(11) NOT NULL DEFAULT '0',
  `AmnesiaChance` int(11) NOT NULL DEFAULT '0',
  `Message1` text,
  `Message2` text,
  `Message3` text,
  `Message4` text,
  `InstrumentRequirement` int(11) NOT NULL DEFAULT '0',
  `SpellGroup` int(11) NOT NULL DEFAULT '0',
  `EffectGroup` int(11) NOT NULL DEFAULT '0',
  `SubSpellID` int(11) NOT NULL DEFAULT '0',
  `MoveCast` tinyint(1) NOT NULL DEFAULT '0',
  `Uninterruptible` tinyint(1) NOT NULL DEFAULT '0',
  `IsFocus` tinyint(1) NOT NULL DEFAULT '0',
  `SharedTimerGroup` int(11) NOT NULL DEFAULT '0',
  `IsPrimary` tinyint(1) NOT NULL DEFAULT '0',
  `IsSecondary` tinyint(1) NOT NULL DEFAULT '0',
  `AllowBolt` tinyint(1) NOT NULL DEFAULT '0',
  `PackageID` text,
  `TooltipId` smallint(5) unsigned NOT NULL DEFAULT '0',
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Spell_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`Spell_ID`),
  UNIQUE KEY `U_Spell_SpellID` (`SpellID`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
