CREATE TABLE IF NOT EXISTS `Account` (`Name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Password` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`CreationDate` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LastLogin` DATETIME DEFAULT NULL, 
`Realm` INT(11) NOT NULL DEFAULT 0, 
`PrivLevel` UNSIGNED INT(10) NOT NULL DEFAULT 0, 
`Status` INT(11) NOT NULL DEFAULT 0, 
`Mail` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastLoginIP` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`LastClientVersion` TEXT DEFAULT NULL COLLATE NOCASE, 
`Language` TEXT DEFAULT NULL COLLATE NOCASE, 
`IsMuted` TINYINT(1) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Account_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`Name`));
CREATE UNIQUE INDEX `U_Account_Account_ID` ON `Account` (`Account_ID`);
CREATE INDEX `I_Account_LastLoginIP` ON `Account` (`LastLoginIP`);
