CREATE TABLE IF NOT EXISTS `Appeal` (`Name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Account` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Severity` INT(11) NOT NULL DEFAULT 0, 
`Status` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Timestamp` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Text` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Appeal_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Appeal_ID`));
CREATE INDEX `I_Appeal_Name` ON `Appeal` (`Name`);
CREATE INDEX `I_Appeal_Account` ON `Appeal` (`Account`);
