DROP TABLE IF EXISTS `ArtifactXItem`;

CREATE TABLE `ArtifactXItem` (`ArtifactID` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`ItemID` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Version` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Realm` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`ArtifactXItem_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`ArtifactXItem_ID`));
