CREATE TABLE IF NOT EXISTS `AutoXMLUpdate` (`AutoXMLUpdateID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`FilePackage` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`FileHash` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LoadResult` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE INDEX `I_AutoXMLUpdate_FilePackage` ON `AutoXMLUpdate` (`FilePackage`);
CREATE INDEX `I_AutoXMLUpdate_FileHash` ON `AutoXMLUpdate` (`FileHash`);
