CREATE TABLE IF NOT EXISTS `Ban` (`Author` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Type` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Ip` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Account` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`DateBan` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Reason` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Ban_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Ban_ID`));
CREATE INDEX `I_Ban_Type` ON `Ban` (`Type`);
CREATE INDEX `I_Ban_Ip` ON `Ban` (`Ip`);
CREATE INDEX `I_Ban_Account` ON `Ban` (`Account`);
