DROP TABLE IF EXISTS `Battleground`;

CREATE TABLE `Battleground` (`RegionID` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`MinLevel` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`MaxLevel` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`MaxRealmLevel` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Battleground_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Battleground_ID`));
