DROP TABLE IF EXISTS `BindPoint`;

CREATE TABLE `BindPoint` (`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Radius` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Region` INT(11) NOT NULL DEFAULT 0, 
`Realm` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`BindPoint_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`BindPoint_ID`));
