CREATE TABLE IF NOT EXISTS `CharacterXDataQuest` (`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`Character_ID` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`DataQuestID` INT(11) NOT NULL DEFAULT 0, 
`Step` SMALLINT(6) NOT NULL DEFAULT 0, 
`Count` SMALLINT(6) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE INDEX `I_CharacterXDataQuest_Character_ID` ON `CharacterXDataQuest` (`DataQuestID`, `Character_ID`);
