DROP TABLE IF EXISTS `ClassXRealmAbility`;

CREATE TABLE `ClassXRealmAbility` (`CharClass` INT(11) NOT NULL DEFAULT 0, 
`AbilityKey` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`ClassXRealmAbility_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`ClassXRealmAbility_ID`));
