CREATE TABLE IF NOT EXISTS `DBHouseCharsXPerms` (`HouseNumber` INT(11) NOT NULL DEFAULT 0, 
`PermissionType` INT(11) NOT NULL DEFAULT 0, 
`TargetName` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`DisplayName` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`PermissionLevel` INT(11) NOT NULL DEFAULT 0, 
`CreationTime` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`DBHouseCharsXPerms_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`DBHouseCharsXPerms_ID`));
