DROP TABLE IF EXISTS `DBIndoorItem`;

CREATE TABLE `DBIndoorItem` (`HouseNumber` INT(11) NOT NULL DEFAULT 0, 
`Model` INT(11) NOT NULL DEFAULT 0, 
`Position` INT(11) NOT NULL DEFAULT 0, 
`Placemode` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`BaseItemID` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Color` INT(11) NOT NULL DEFAULT 0, 
`Emblem` INT(11) NOT NULL DEFAULT 0, 
`Rotation` INT(11) NOT NULL DEFAULT 0, 
`Size` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`DBIndoorItem_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`DBIndoorItem_ID`));
CREATE INDEX `I_DBIndoorItem_HouseNumber` ON `DBIndoorItem` (`HouseNumber`);
