DROP TABLE IF EXISTS `DBOutdoorItem`;

CREATE TABLE `DBOutdoorItem` (`HouseNumber` INT(11) NOT NULL DEFAULT 0, 
`Model` INT(11) NOT NULL DEFAULT 0, 
`Position` INT(11) NOT NULL DEFAULT 0, 
`Rotation` INT(11) NOT NULL DEFAULT 0, 
`BaseItemID` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`DBOutdoorItem_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`DBOutdoorItem_ID`));
CREATE INDEX `I_DBOutdoorItem_HouseNumber` ON `DBOutdoorItem` (`HouseNumber`);
