DROP TABLE IF EXISTS `Door`;

CREATE TABLE `Door` (`Name` TEXT DEFAULT NULL COLLATE NOCASE, 
`Type` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`InternalID` INT(11) NOT NULL DEFAULT 0, 
`Guild` TEXT DEFAULT NULL COLLATE NOCASE, 
`Level` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Flags` UNSIGNED INT(10) NOT NULL DEFAULT 0, 
`Locked` INT(11) NOT NULL DEFAULT 0, 
`Health` INT(11) NOT NULL DEFAULT 0, 
`MaxHealth` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Door_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Door_ID`));
CREATE INDEX `I_Door_InternalID` ON `Door` (`InternalID`);
