DROP TABLE IF EXISTS `Faction`;

CREATE TABLE `Faction` (`ID` INT(11) NOT NULL DEFAULT 0, 
`Name` TEXT DEFAULT NULL COLLATE NOCASE, 
`BaseAggroLevel` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Faction_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`ID`));
CREATE UNIQUE INDEX `U_Faction_Faction_ID` ON `Faction` (`Faction_ID`);
