CREATE TABLE IF NOT EXISTS `GuildAlliance` (`AllianceName` TEXT DEFAULT NULL COLLATE NOCASE, 
`Motd` TEXT DEFAULT NULL COLLATE NOCASE, 
`LeaderGuildID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`GuildAlliance_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`GuildAlliance_ID`));
CREATE UNIQUE INDEX `U_GuildAlliance_LeaderGuildID` ON `GuildAlliance` (`LeaderGuildID`);
