DROP TABLE IF EXISTS `InstanceXElement`;

CREATE TABLE `InstanceXElement` (`InstanceID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`ClassType` TEXT DEFAULT NULL COLLATE NOCASE, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`NPCTemplate` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`InstanceXElement_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`InstanceXElement_ID`));
CREATE INDEX `I_InstanceXElement_InstanceID` ON `InstanceXElement` (`InstanceID`);
