CREATE TABLE IF NOT EXISTS `Inventory` (`OwnerID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`OwnerLot` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`ITemplate_Id` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`UTemplate_Id` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`IsCrafted` TINYINT(1) NOT NULL DEFAULT 0, 
`Creator` TEXT DEFAULT NULL COLLATE NOCASE, 
`SlotPosition` INT(11) NOT NULL DEFAULT 0, 
`Count` INT(11) NOT NULL DEFAULT 0, 
`SellPrice` INT(11) NOT NULL DEFAULT 0, 
`Experience` BIGINT(20) NOT NULL DEFAULT 0, 
`Color` INT(11) NOT NULL DEFAULT 0, 
`Emblem` INT(11) NOT NULL DEFAULT 0, 
`Extension` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Condition` INT(11) NOT NULL DEFAULT 0, 
`Durability` INT(11) NOT NULL DEFAULT 0, 
`PoisonSpellID` INT(11) NOT NULL DEFAULT 0, 
`PoisonMaxCharges` INT(11) NOT NULL DEFAULT 0, 
`PoisonCharges` INT(11) NOT NULL DEFAULT 0, 
`Charges` INT(11) NOT NULL DEFAULT 0, 
`Charges1` INT(11) NOT NULL DEFAULT 0, 
`Cooldown` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Inventory_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Inventory_ID`));
CREATE INDEX `I_Inventory_OwnerID` ON `Inventory` (`OwnerID`);
CREATE INDEX `I_Inventory_ITemplate_Id` ON `Inventory` (`ITemplate_Id`);
CREATE INDEX `I_Inventory_UTemplate_Id` ON `Inventory` (`UTemplate_Id`);
CREATE INDEX `I_Inventory_SlotPosition` ON `Inventory` (`SlotPosition`);
