DROP TABLE IF EXISTS `Keep`;

CREATE TABLE `Keep` (`KeepID` INT(11) NOT NULL DEFAULT 0, 
`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Region` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Level` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`ClaimedGuildName` TEXT DEFAULT NULL COLLATE NOCASE, 
`AlbionDifficultyLevel` INT(11) NOT NULL DEFAULT 0, 
`MidgardDifficultyLevel` INT(11) NOT NULL DEFAULT 0, 
`HiberniaDifficultyLevel` INT(11) NOT NULL DEFAULT 0, 
`OriginalRealm` INT(11) NOT NULL DEFAULT 0, 
`KeepType` INT(11) NOT NULL DEFAULT 0, 
`BaseLevel` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`SkinType` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`CreateInfo` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Keep_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`KeepID`));
CREATE UNIQUE INDEX `U_Keep_Keep_ID` ON `Keep` (`Keep_ID`);
