DROP TABLE IF EXISTS `LanguageNPC`;

CREATE TABLE `LanguageNPC` (`Name` TEXT DEFAULT NULL COLLATE NOCASE, 
`Suffix` TEXT DEFAULT NULL COLLATE NOCASE, 
`GuildName` TEXT DEFAULT NULL COLLATE NOCASE, 
`ExamineArticle` TEXT DEFAULT NULL COLLATE NOCASE, 
`MessageArticle` TEXT DEFAULT NULL COLLATE NOCASE, 
`TranslationId` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Language` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Tag` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LanguageNPC_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`LanguageNPC_ID`));
CREATE INDEX `I_LanguageNPC_TranslationId` ON `LanguageNPC` (`TranslationId`);
CREATE INDEX `I_LanguageNPC_Language` ON `LanguageNPC` (`Language`);
