DROP TABLE IF EXISTS `LanguageArea`;

CREATE TABLE `LanguageArea` (`Description` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`ScreenDescription` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`TranslationId` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Language` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Tag` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LanguageArea_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`LanguageArea_ID`));
CREATE INDEX `I_LanguageArea_TranslationId` ON `LanguageArea` (`TranslationId`);
CREATE INDEX `I_LanguageArea_Language` ON `LanguageArea` (`Language`);
