DROP TABLE IF EXISTS `LanguageZone`;

CREATE TABLE `LanguageZone` (`Description` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`ScreenDescription` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`TranslationId` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Language` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Tag` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LanguageZone_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`LanguageZone_ID`));
CREATE INDEX `I_LanguageZone_TranslationId` ON `LanguageZone` (`TranslationId`);
CREATE INDEX `I_LanguageZone_Language` ON `LanguageZone` (`Language`);
