DROP TABLE IF EXISTS `LineXSpell`;

CREATE TABLE `LineXSpell` (`LineName` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`SpellID` INT(11) NOT NULL DEFAULT 0, 
`Level` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LineXSpell_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`PackageID` TEXT DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`LineXSpell_ID`));
CREATE INDEX `I_LineXSpell_LineName` ON `LineXSpell` (`LineName`);
