DROP TABLE IF EXISTS `LootGenerator`;

CREATE TABLE `LootGenerator` (`MobName` TEXT DEFAULT NULL COLLATE NOCASE, 
`MobGuild` TEXT DEFAULT NULL COLLATE NOCASE, 
`MobFaction` TEXT DEFAULT NULL COLLATE NOCASE, 
`RegionID` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`LootGeneratorClass` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`ExclusivePriority` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LootGenerator_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`LootGenerator_ID`));
