DROP TABLE IF EXISTS `MobXAmbientBehaviour`;

CREATE TABLE `MobXAmbientBehaviour` (`Source` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Trigger` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Emote` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Text` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Chance` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Voice` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`MobXAmbientBehaviour_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`MobXAmbientBehaviour_ID`));
CREATE INDEX `I_MobXAmbientBehaviour_Source` ON `MobXAmbientBehaviour` (`Source`);
