CREATE TABLE IF NOT EXISTS `News` (`CreationDate` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Type` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`Text` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`News_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`News_ID`));
