DROP TABLE IF EXISTS `NPCEquipment`;

CREATE TABLE `NPCEquipment` (`TemplateID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Slot` INT(11) NOT NULL DEFAULT 0, 
`Model` INT(11) NOT NULL DEFAULT 0, 
`Color` INT(11) NOT NULL DEFAULT 0, 
`Effect` INT(11) NOT NULL DEFAULT 0, 
`Extension` INT(11) NOT NULL DEFAULT 0, 
`Emblem` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`NPCEquipment_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`NPCEquipment_ID`));
CREATE INDEX `I_NPCEquipment_TemplateID` ON `NPCEquipment` (`TemplateID`);
