DROP TABLE IF EXISTS `Path`;

CREATE TABLE `Path` (`PathID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`PathType` INT(11) NOT NULL DEFAULT 0, 
`RegionID` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Path_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Path_ID`));
CREATE UNIQUE INDEX `U_Path_PathID` ON `Path` (`PathID`);
