CREATE TABLE IF NOT EXISTS `PlayerBoats` (`BoatID` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`BoatOwner` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`BoatName` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`BoatModel` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`BoatMaxSpeedBase` SMALLINT(6) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`PlayerBoats_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`BoatName`));
CREATE UNIQUE INDEX `U_PlayerBoats_PlayerBoats_ID` ON `PlayerBoats` (`PlayerBoats_ID`);
