DROP TABLE IF EXISTS `Race`;

CREATE TABLE `Race` (`ID` INT(11) NOT NULL DEFAULT 0, 
`Name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`ResistBody` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistCold` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistCrush` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistEnergy` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistHeat` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistMatter` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistNatural` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistSlash` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistSpirit` SMALLINT(3) NOT NULL DEFAULT 0, 
`ResistThrust` SMALLINT(3) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Race_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Race_ID`));
CREATE UNIQUE INDEX `U_Race_ID` ON `Race` (`ID`);
CREATE UNIQUE INDEX `U_Race_Name` ON `Race` (`Name`);
