DROP TABLE IF EXISTS `Regions`;

CREATE TABLE `Regions` (`RegionID` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Description` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`IP` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Port` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Expansion` INT(11) NOT NULL DEFAULT 0, 
`HousingEnabled` TINYINT(1) NOT NULL DEFAULT 0, 
`DivingEnabled` TINYINT(1) NOT NULL DEFAULT 0, 
`WaterLevel` INT(11) NOT NULL DEFAULT 0, 
`ClassType` VARCHAR(200) NOT NULL DEFAULT '' COLLATE NOCASE, 
`IsFrontier` TINYINT(1) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Regions_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`RegionID`));
CREATE UNIQUE INDEX `U_Regions_Regions_ID` ON `Regions` (`Regions_ID`);
