CREATE TABLE IF NOT EXISTS `ServerProperty` (`Category` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Key` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Description` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`DefaultValue` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Value` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`ServerProperty_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`Key`));
CREATE UNIQUE INDEX `U_ServerProperty_ServerProperty_ID` ON `ServerProperty` (`ServerProperty_ID`);
