CREATE TABLE IF NOT EXISTS `serverstats` (`StatDate` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Clients` INT(11) NOT NULL DEFAULT 0, 
`CPU` FLOAT NOT NULL DEFAULT 0, 
`Upload` INT(11) NOT NULL DEFAULT 0, 
`Download` INT(11) NOT NULL DEFAULT 0, 
`Memory` BIGINT(20) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`serverstats_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`serverstats_ID`));
