DROP TABLE IF EXISTS `Specialization`;

CREATE TABLE `Specialization` (`SpecializationID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`KeyName` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Icon` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Description` TEXT DEFAULT NULL COLLATE NOCASE, 
`Implementation` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE UNIQUE INDEX `U_Specialization_KeyName` ON `Specialization` (`KeyName`);
