DROP TABLE IF EXISTS `StarterEquipment`;

CREATE TABLE `StarterEquipment` (`StarterEquipmentID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`Class` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`TemplateID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
