DROP TABLE IF EXISTS `StyleXSpell`;

CREATE TABLE `StyleXSpell` (`SpellID` INT(11) NOT NULL DEFAULT 0, 
`ClassID` INT(11) NOT NULL DEFAULT 0, 
`StyleID` INT(11) NOT NULL DEFAULT 0, 
`Chance` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`StyleXSpell_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`StyleXSpell_ID`));
CREATE INDEX `I_StyleXSpell_StyleID` ON `StyleXSpell` (`StyleID`);
