DROP TABLE IF EXISTS `Style`;

CREATE TABLE `Style` (`StyleID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`ID` INT(11) NOT NULL DEFAULT 0, 
`ClassId` INT(11) NOT NULL DEFAULT 0, 
`Name` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`SpecKeyName` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`SpecLevelRequirement` INT(11) NOT NULL DEFAULT 0, 
`Icon` INT(11) NOT NULL DEFAULT 0, 
`EnduranceCost` INT(11) NOT NULL DEFAULT 0, 
`StealthRequirement` TINYINT(1) NOT NULL DEFAULT 0, 
`OpeningRequirementType` INT(11) NOT NULL DEFAULT 0, 
`OpeningRequirementValue` INT(11) NOT NULL DEFAULT 0, 
`AttackResultRequirement` INT(11) NOT NULL DEFAULT 0, 
`WeaponTypeRequirement` INT(11) NOT NULL DEFAULT 0, 
`GrowthOffset` DOUBLE NOT NULL DEFAULT 0, 
`GrowthRate` DOUBLE NOT NULL DEFAULT 0, 
`BonusToHit` INT(11) NOT NULL DEFAULT 0, 
`BonusToDefense` INT(11) NOT NULL DEFAULT 0, 
`TwoHandAnimation` INT(11) NOT NULL DEFAULT 0, 
`RandomProc` TINYINT(1) NOT NULL DEFAULT 0, 
`ArmorHitLocation` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE INDEX `I_Style_SpecKeyName` ON `Style` (`SpecKeyName`);
