CREATE TABLE IF NOT EXISTS `Task` (`Character_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`TimeOut` DATETIME DEFAULT NULL, 
`TaskType` TEXT DEFAULT NULL COLLATE NOCASE, 
`TasksDone` INT(11) NOT NULL DEFAULT 0, 
`CustomPropertiesString` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Task_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`Character_ID`));
CREATE UNIQUE INDEX `U_Task_Task_ID` ON `Task` (`Task_ID`);
