DROP TABLE IF EXISTS `WorldObject`;

CREATE TABLE `WorldObject` (`ClassType` TEXT DEFAULT NULL COLLATE NOCASE, 
`TranslationId` TEXT DEFAULT NULL COLLATE NOCASE, 
`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`ExamineArticle` TEXT DEFAULT NULL COLLATE NOCASE, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Region` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Model` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Emblem` INT(11) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`RespawnInterval` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`WorldObject_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`WorldObject_ID`));
CREATE INDEX `I_WorldObject_Region` ON `WorldObject` (`Region`);
