DROP TABLE IF EXISTS `Zones`;

CREATE TABLE `Zones` (`ZoneID` INT(11) NOT NULL DEFAULT 0, 
`RegionID` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`IsLava` TINYINT(1) NOT NULL DEFAULT 0, 
`DivingFlag` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`WaterLevel` INT(11) NOT NULL DEFAULT 0, 
`OffsetY` INT(11) NOT NULL DEFAULT 0, 
`OffsetX` INT(11) NOT NULL DEFAULT 0, 
`Width` INT(11) NOT NULL DEFAULT 0, 
`Height` INT(11) NOT NULL DEFAULT 0, 
`Experience` INT(11) NOT NULL DEFAULT 0, 
`Realmpoints` INT(11) NOT NULL DEFAULT 0, 
`Bountypoints` INT(11) NOT NULL DEFAULT 0, 
`Coin` INT(11) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED TINYINT(3) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Zones_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`ZoneID`));
CREATE UNIQUE INDEX `U_Zones_Zones_ID` ON `Zones` (`Zones_ID`);
CREATE INDEX `I_Zones_RegionID` ON `Zones` (`RegionID`);
