package main

func getAllTables() []Table {
	allTables := make([]Table, 0)
	t := newTable("Ability")
	t.Static = true
	t.AddPrimary("AbilityID", "int(11)").NotNullable()
	t.AddUnique("KeyName", "varchar(100)").NotNullable()
	t.Add("Name", "varchar(255)").NotNullable()
	t.Add("InternalID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Description", "text").NotNullable()
	t.Add("IconID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Implementation", "varchar(255)").SetDefault("NULL")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 241
	allTables = append(allTables, *t)

	t = newTable("Account")
	t.AddPrimary("Name", "varchar(255)").NotNullable()
	t.Add("Password", "text").NotNullable()
	t.Add("CreationDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("LastLogin", "datetime").SetDefault("NULL")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("PrivLevel", "int(10) unsigned").NotNullable().SetDefault("0")
	t.Add("Status", "int(11)").NotNullable().SetDefault("0")
	t.Add("Mail", "text")
	t.AddWithIndex("LastLoginIP", "varchar(255)").SetDefault("NULL")
	t.Add("LastClientVersion", "text")
	t.Add("Language", "text")
	t.Add("IsMuted", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Account_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("AccountXCustomParam")
	t.AddWithIndex("Name", "varchar(255)").NotNullable()
	t.AddWithIndex("KeyName", "varchar(100)").NotNullable()
	t.Add("Value", "varchar(255)").SetDefault("NULL")
	t.AddPrimary("CustomParamID", "int(11)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("Appeal")
	t.AddWithIndex("Name", "varchar(255)").NotNullable()
	t.AddWithIndex("Account", "varchar(255)").NotNullable()
	t.Add("Severity", "int(11)").NotNullable().SetDefault("0")
	t.Add("Status", "text").NotNullable()
	t.Add("Timestamp", "text").NotNullable()
	t.Add("Text", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Appeal_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Area")
	t.Static = true
	t.Add("TranslationId", "text")
	t.Add("Description", "text").NotNullable()
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Radius", "int(11)").NotNullable().SetDefault("0")
	t.Add("Region", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("ClassType", "text")
	t.Add("CanBroadcast", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Sound", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("CheckLOS", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Points", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Area_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ArtifactBonus")
	t.Static = true
	t.Add("ArtifactID", "text").NotNullable()
	t.Add("BonusID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("ArtifactBonus_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Artifact")
	t.Static = true
	t.Add("ArtifactID", "text").NotNullable()
	t.Add("EncounterID", "text").NotNullable()
	t.Add("QuestID", "text").NotNullable()
	t.Add("Zone", "text").NotNullable()
	t.Add("ScholarID", "text").NotNullable()
	t.Add("ReuseTimer", "int(11)").NotNullable().SetDefault("0")
	t.Add("XPRate", "int(11)").NotNullable().SetDefault("0")
	t.Add("BookID", "text").NotNullable()
	t.Add("BookModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Scroll1", "text").NotNullable()
	t.Add("Scroll2", "text").NotNullable()
	t.Add("Scroll3", "text").NotNullable()
	t.Add("Scroll12", "text").NotNullable()
	t.Add("Scroll13", "text").NotNullable()
	t.Add("Scroll23", "text").NotNullable()
	t.Add("ScrollModel1", "int(11)").NotNullable().SetDefault("0")
	t.Add("ScrollModel2", "int(11)").NotNullable().SetDefault("0")
	t.Add("ScrollLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MessageUse", "text").NotNullable()
	t.Add("MessageCombineScrolls", "text").NotNullable()
	t.Add("MessageCombineBook", "text").NotNullable()
	t.Add("MessageReceiveScrolls", "text").NotNullable()
	t.Add("MessageReceiveBook", "text").NotNullable()
	t.Add("Credit", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Artifact_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ArtifactXItem")
	t.Static = true
	t.Add("ArtifactID", "text").NotNullable()
	t.Add("ItemID", "text").NotNullable()
	t.Add("Version", "text").NotNullable()
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("ArtifactXItem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("AuditEntry")
	t.Add("AuditTime", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("AccountID", "text")
	t.Add("RemoteHost", "text")
	t.Add("AuditType", "int(11)").NotNullable().SetDefault("0")
	t.Add("AuditSubtype", "int(11)").NotNullable().SetDefault("0")
	t.Add("OldValue", "text")
	t.Add("NewValue", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("AuditEntry_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("AutoXMLUpdate")
	t.AddPrimary("AutoXMLUpdateID", "int(11)").NotNullable()
	t.AddWithIndex("FilePackage", "varchar(255)").NotNullable()
	t.AddWithIndex("FileHash", "varchar(255)").NotNullable()
	t.Add("LoadResult", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 4
	allTables = append(allTables, *t)

	t = newTable("Ban")
	t.Add("Author", "text").NotNullable()
	t.AddWithIndex("Type", "varchar(255)").NotNullable()
	t.AddWithIndex("Ip", "varchar(255)").NotNullable()
	t.AddWithIndex("Account", "varchar(255)").NotNullable()
	t.Add("DateBan", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("Reason", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Ban_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Battleground")
	t.Static = true
	t.Add("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("MinLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MaxLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MaxRealmLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Battleground_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("BindPoint")
	t.Static = true
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Radius", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Region", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("BindPoint_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("BugReport")
	t.AddPrimary("ID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Message", "text").NotNullable()
	t.Add("Submitter", "text").NotNullable()
	t.Add("DateSubmitted", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("ClosedBy", "text").NotNullable()
	t.Add("DateClosed", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("Category", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("BugReport_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("CharacterXDataQuest")
	t.AddPrimary("ID", "int(11)").NotNullable()
	t.AddWithIndex("Character_ID", "varchar(100)").NotNullable()
	t.Add("DataQuestID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Step", "smallint(6)").NotNullable().SetDefault("0")
	t.Add("Count", "smallint(6)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	t.Indexes[0].Keys = append([]*TableColumn{t.Columns[2]}, t.Indexes[0].Keys...)
	allTables = append(allTables, *t)

	t = newTable("CharacterXMasterLevel")
	t.AddWithIndex("Character_ID", "varchar(255)").NotNullable()
	t.Add("MLLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MLStep", "int(11)").NotNullable().SetDefault("0")
	t.Add("StepCompleted", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ValidationDate", "datetime").SetDefault("NULL")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("CharacterXMasterLevel_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("CharacterXOneTimeDrop")
	t.AddWithIndex("CharacterID", "varchar(100)").NotNullable()
	t.AddWithIndex("ItemTemplateID", "varchar(100)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("CharacterXOneTimeDrop_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ClassXRealmAbility")
	t.Static = true
	t.Add("CharClass", "int(11)").NotNullable().SetDefault("0")
	t.Add("AbilityKey", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("ClassXRealmAbility_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ClassXSpecialization")
	t.Static = true
	t.AddPrimary("ClassXSpecializationID", "int(11)").NotNullable()
	t.AddWithIndex("ClassID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("SpecKeyName", "varchar(100)").NotNullable()
	t.AddWithIndex("LevelAcquired", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 538
	allTables = append(allTables, *t)

	t = newTable("CraftedItem")
	t.Static = true
	t.AddPrimary("CraftedItemID", "varchar(255)").NotNullable()
	t.AddWithIndex("Id_nb", "varchar(255)").NotNullable()
	t.Add("CraftingLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("CraftingSkillType", "int(11)").NotNullable().SetDefault("0")
	t.Add("MakeTemplated", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("CraftedItem_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("CraftedXItem")
	t.Static = true
	t.AddWithIndex("CraftedItemId_nb", "varchar(255)").NotNullable()
	t.Add("IngredientId_nb", "text").NotNullable()
	t.Add("Count", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("CraftedXItem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DataQuest")
	t.Static = true
	t.AddPrimary("ID", "int(11)").NotNullable()
	t.Add("Name", "varchar(255)").NotNullable()
	t.Add("StartType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("StartName", "varchar(100)").NotNullable()
	t.Add("StartRegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("AcceptText", "varchar(100)").SetDefault("NULL")
	t.Add("Description", "text")
	t.Add("SourceName", "text")
	t.Add("SourceText", "text")
	t.Add("StepType", "text")
	t.Add("StepText", "text")
	t.Add("StepItemTemplates", "text")
	t.Add("AdvanceText", "text")
	t.Add("TargetName", "text")
	t.Add("TargetText", "text")
	t.Add("CollectItemTemplate", "text")
	t.Add("MaxCount", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("MinLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MaxLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("RewardMoney", "text")
	t.Add("RewardXP", "text")
	t.Add("RewardCLXP", "text")
	t.Add("RewardRP", "text")
	t.Add("RewardBP", "text")
	t.Add("OptionalRewardItemTemplates", "text")
	t.Add("FinalRewardItemTemplates", "text")
	t.Add("FinishText", "text")
	t.Add("QuestDependency", "text")
	t.Add("AllowedClasses", "varchar(200)").SetDefault("NULL")
	t.Add("ClassType", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("DBHouseCharsXPerms")
	t.Add("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("PermissionType", "int(11)").NotNullable().SetDefault("0")
	t.Add("TargetName", "text").NotNullable()
	t.Add("DisplayName", "text").NotNullable()
	t.Add("PermissionLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationTime", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DBHouseCharsXPerms_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DBHousePermissions")
	t.Add("PermissionLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("CanEnterHouse", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Vault1", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Vault2", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Vault3", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Vault4", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("CanChangeExternalAppearance", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ChangeInterior", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ChangeGarden", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("CanBanish", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CanUseMerchants", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CanUseTools", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CanBindInHouse", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ConsignmentMerchant", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("CanPayRent", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DBHousePermissions_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DBHouse")
	t.AddPrimary("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationTime", "datetime").SetDefault("NULL")
	t.Add("Name", "text")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("PorchRoofColor", "int(11)").NotNullable().SetDefault("0")
	t.Add("PorchMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("RoofMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("DoorMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("WallMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("TrussMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("WindowMaterial", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rug1Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rug2Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rug3Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rug4Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("IndoorGuildBanner", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IndoorGuildShield", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OutdoorGuildBanner", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OutdoorGuildShield", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Porch", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OwnerID", "text")
	t.Add("LastPaid", "datetime").SetDefault("NULL")
	t.Add("KeptMoney", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("NoPurge", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildHouse", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildName", "text")
	t.Add("HasConsignment", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("DBHouse_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("DBIndoorItem")
	t.Static = true
	t.AddWithIndex("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Position", "int(11)").NotNullable().SetDefault("0")
	t.Add("Placemode", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("BaseItemID", "text").NotNullable()
	t.Add("Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rotation", "int(11)").NotNullable().SetDefault("0")
	t.Add("Size", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DBIndoorItem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DBOutdoorItem")
	t.Static = true
	t.AddWithIndex("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Position", "int(11)").NotNullable().SetDefault("0")
	t.Add("Rotation", "int(11)").NotNullable().SetDefault("0")
	t.Add("BaseItemID", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DBOutdoorItem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DOLCharactersBackup")
	t.Add("DOLCharacters_ID", "varchar(255)").NotNullable()
	t.AddWithIndex("Name", "varchar(255)").NotNullable()
	t.Add("DeleteDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("HasGravestone", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GravestoneRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("Constitution", "int(11)").NotNullable().SetDefault("0")
	t.Add("Dexterity", "int(11)").NotNullable().SetDefault("0")
	t.Add("Strength", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quickness", "int(11)").NotNullable().SetDefault("0")
	t.Add("Intelligence", "int(11)").NotNullable().SetDefault("0")
	t.Add("Piety", "int(11)").NotNullable().SetDefault("0")
	t.Add("Empathy", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charisma", "int(11)").NotNullable().SetDefault("0")
	t.Add("BountyPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RealmPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RealmLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Experience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MaxEndurance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Health", "int(11)").NotNullable().SetDefault("0")
	t.Add("Mana", "int(11)").NotNullable().SetDefault("0")
	t.Add("Endurance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Concentration", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("AccountName", "varchar(255)").NotNullable()
	t.Add("AccountSlot", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("LastPlayed", "datetime").SetDefault("NULL")
	t.Add("LastName", "text")
	t.AddWithIndex("GuildID", "varchar(255)").SetDefault("NULL")
	t.Add("Gender", "int(11)").NotNullable().SetDefault("0")
	t.Add("Race", "int(11)").NotNullable().SetDefault("0")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("Class", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("CurrentModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Region", "int(11)").NotNullable().SetDefault("0")
	t.Add("ActiveWeaponSlot", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Xpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("Ypos", "int(11)").NotNullable().SetDefault("0")
	t.Add("Zpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindXpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindYpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindZpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHeading", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseXpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseYpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseZpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseHeading", "int(11)").NotNullable().SetDefault("0")
	t.Add("DeathCount", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ConLostAtDeath", "int(11)").NotNullable().SetDefault("0")
	t.Add("Direction", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxSpeed", "int(11)").NotNullable().SetDefault("0")
	t.Add("Copper", "int(11)").NotNullable().SetDefault("0")
	t.Add("Silver", "int(11)").NotNullable().SetDefault("0")
	t.Add("Gold", "int(11)").NotNullable().SetDefault("0")
	t.Add("Platinum", "int(11)").NotNullable().SetDefault("0")
	t.Add("Mithril", "int(11)").NotNullable().SetDefault("0")
	t.Add("SerializedCraftingSkills", "text")
	t.Add("SerializedAbilities", "text")
	t.Add("SerializedSpecs", "text")
	t.Add("SerializedRealmAbilities", "text")
	t.Add("DisabledSpells", "text")
	t.Add("DisabledAbilities", "text")
	t.Add("SerializedFriendsList", "text")
	t.Add("SerializedIgnoreList", "text")
	t.Add("IsCloakHoodUp", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsCloakInvisible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsHelmInvisible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("SpellQueue", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsLevelSecondStage", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("FlagClassName", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Advisor", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildRank", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("PlayedTime", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("DeathTime", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RespecAmountAllSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountSingleSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountRealmSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountDOL", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountChampionSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsLevelRespecUsed", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("RespecBought", "int(11)").NotNullable().SetDefault("0")
	t.Add("SafetyFlag", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CraftingPrimarySkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("CancelStyle", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsAnonymous", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CustomisationStep", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EyeSize", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LipSize", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EyeColor", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("HairColor", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("FaceType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("HairStyle", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MoodType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("UsedLevelCommand", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CurrentTitleType", "text")
	t.Add("KillsAlbionPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsAlbionDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsAlbionSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedKeeps", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedTowers", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedRelics", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsDragon", "int(11)").NotNullable().SetDefault("0")
	t.Add("DeathsPvP", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsLegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsEpicBoss", "int(11)").NotNullable().SetDefault("0")
	t.Add("GainXP", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GainRP", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Autoloot", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastFreeLeveled", "datetime").SetDefault("NULL")
	t.Add("LastFreeLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("GuildNote", "text")
	t.Add("ShowXFireInfo", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("NoHelp", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ShowGuildLogins", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Champion", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ChampionLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("ChampionExperience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("ML", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MLExperience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MLLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MLGranted", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("RPFlag", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IgnoreStatistics", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("NotDisplayedInHerald", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ActiveSaddleBags", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DOLCharactersBackup_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DOLCharactersBackupXCustomParam")
	t.AddWithIndex("DOLCharactersObjectId", "varchar(255)").NotNullable()
	t.AddWithIndex("KeyName", "varchar(100)").NotNullable()
	t.Add("Value", "varchar(255)").SetDefault("NULL")
	t.AddPrimary("CustomParamID", "int(11)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("DOLCharacters")
	t.Add("HasGravestone", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GravestoneRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("Constitution", "int(11)").NotNullable().SetDefault("0")
	t.Add("Dexterity", "int(11)").NotNullable().SetDefault("0")
	t.Add("Strength", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quickness", "int(11)").NotNullable().SetDefault("0")
	t.Add("Intelligence", "int(11)").NotNullable().SetDefault("0")
	t.Add("Piety", "int(11)").NotNullable().SetDefault("0")
	t.Add("Empathy", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charisma", "int(11)").NotNullable().SetDefault("0")
	t.Add("BountyPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RealmPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RealmLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Experience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MaxEndurance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Health", "int(11)").NotNullable().SetDefault("0")
	t.Add("Mana", "int(11)").NotNullable().SetDefault("0")
	t.Add("Endurance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Concentration", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("AccountName", "varchar(255)").NotNullable()
	t.Add("AccountSlot", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("LastPlayed", "datetime").SetDefault("NULL")
	t.AddUnique("Name", "varchar(255)").NotNullable()
	t.Add("LastName", "text")
	t.AddWithIndex("GuildID", "varchar(255)").SetDefault("NULL")
	t.Add("Gender", "int(11)").NotNullable().SetDefault("0")
	t.Add("Race", "int(11)").NotNullable().SetDefault("0")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("Class", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreationModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("CurrentModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Region", "int(11)").NotNullable().SetDefault("0")
	t.Add("ActiveWeaponSlot", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Xpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("Ypos", "int(11)").NotNullable().SetDefault("0")
	t.Add("Zpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindXpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindYpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindZpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHeading", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseXpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseYpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseZpos", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("BindHouseHeading", "int(11)").NotNullable().SetDefault("0")
	t.Add("DeathCount", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ConLostAtDeath", "int(11)").NotNullable().SetDefault("0")
	t.Add("Direction", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxSpeed", "int(11)").NotNullable().SetDefault("0")
	t.Add("Copper", "int(11)").NotNullable().SetDefault("0")
	t.Add("Silver", "int(11)").NotNullable().SetDefault("0")
	t.Add("Gold", "int(11)").NotNullable().SetDefault("0")
	t.Add("Platinum", "int(11)").NotNullable().SetDefault("0")
	t.Add("Mithril", "int(11)").NotNullable().SetDefault("0")
	t.Add("SerializedCraftingSkills", "text")
	t.Add("SerializedAbilities", "text")
	t.Add("SerializedSpecs", "text")
	t.Add("SerializedRealmAbilities", "text")
	t.Add("DisabledSpells", "text")
	t.Add("DisabledAbilities", "text")
	t.Add("SerializedFriendsList", "text")
	t.Add("SerializedIgnoreList", "text")
	t.Add("IsCloakHoodUp", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsCloakInvisible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsHelmInvisible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("SpellQueue", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsLevelSecondStage", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("FlagClassName", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Advisor", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildRank", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("PlayedTime", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("DeathTime", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("RespecAmountAllSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountSingleSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountRealmSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountDOL", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespecAmountChampionSkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsLevelRespecUsed", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("RespecBought", "int(11)").NotNullable().SetDefault("0")
	t.Add("SafetyFlag", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CraftingPrimarySkill", "int(11)").NotNullable().SetDefault("0")
	t.Add("CancelStyle", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsAnonymous", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CustomisationStep", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EyeSize", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LipSize", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EyeColor", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("HairColor", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("FaceType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("HairStyle", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MoodType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("UsedLevelCommand", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CurrentTitleType", "text")
	t.Add("KillsAlbionPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaPlayers", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsAlbionDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaDeathBlows", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsAlbionSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsMidgardSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsHiberniaSolo", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedKeeps", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedTowers", "int(11)").NotNullable().SetDefault("0")
	t.Add("CapturedRelics", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsDragon", "int(11)").NotNullable().SetDefault("0")
	t.Add("DeathsPvP", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsLegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("KillsEpicBoss", "int(11)").NotNullable().SetDefault("0")
	t.Add("GainXP", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GainRP", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Autoloot", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastFreeLeveled", "datetime").SetDefault("NULL")
	t.Add("LastFreeLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("GuildNote", "text")
	t.Add("ShowXFireInfo", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("NoHelp", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ShowGuildLogins", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Champion", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ChampionLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("ChampionExperience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("ML", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("MLExperience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MLLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MLGranted", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("RPFlag", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IgnoreStatistics", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("NotDisplayedInHerald", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ActiveSaddleBags", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("DOLCharacters_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DOLCharactersXCustomParam")
	t.AddWithIndex("DOLCharactersObjectId", "varchar(255)").NotNullable()
	t.AddWithIndex("KeyName", "varchar(100)").NotNullable()
	t.Add("Value", "varchar(255)").SetDefault("NULL")
	t.AddPrimary("CustomParamID", "int(11)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("Door")
	t.Static = true
	t.Add("Name", "text")
	t.Add("Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("InternalID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Guild", "text")
	t.Add("Level", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Flags", "int(10) unsigned").NotNullable().SetDefault("0")
	t.Add("Locked", "int(11)").NotNullable().SetDefault("0")
	t.Add("Health", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxHealth", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Door_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("DropTemplateXItemTemplate")
	t.Static = true
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.AddWithIndex("TemplateName", "varchar(255)").NotNullable()
	t.Add("ItemTemplateID", "text").NotNullable()
	t.Add("Chance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Count", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("FactionAggroLevel")
	t.Static = true
	t.AddWithIndex("CharacterID", "varchar(100)").NotNullable()
	t.Add("FactionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("AggroLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("FactionAggroLevel_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Faction")
	t.Static = true
	t.AddPrimary("ID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Name", "text")
	t.Add("BaseAggroLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Faction_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("GuildAlliance")
	t.Add("AllianceName", "text")
	t.Add("Motd", "text")
	t.AddUnique("LeaderGuildID", "varchar(255)").SetDefault("NULL")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("GuildAlliance_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("GuildRank")
	t.AddWithIndex("GuildID", "varchar(255)").SetDefault("NULL")
	t.Add("Title", "text")
	t.Add("RankLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Alli", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Emblem", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Buff", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GcHear", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GcSpeak", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OcHear", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OcSpeak", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("AcHear", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("AcSpeak", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Invite", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Promote", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Remove", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("View", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Claim", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Upgrade", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Release", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Dues", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Withdraw", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("GuildRank_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Guild")
	t.AddUnique("GuildID", "varchar(255)").SetDefault("NULL")
	t.AddWithIndex("GuildName", "varchar(255)").SetDefault("NULL")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("GuildBanner", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildBannerLostTime", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("Motd", "text")
	t.Add("oMotd", "text")
	t.AddWithIndex("AllianceID", "varchar(255)").SetDefault("NULL")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("RealmPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("BountyPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("Webpage", "text")
	t.Add("Email", "text")
	t.Add("Dues", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Bank", "double").NotNullable().SetDefault("0")
	t.Add("DuesPercent", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("HaveGuildHouse", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("GuildHouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("GuildLevel", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("BonusType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("BonusStartTime", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("MeritPoints", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Guild_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("HouseConsignmentMerchant")
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.AddWithIndex("OwnerID", "varchar(128)").NotNullable()
	t.AddWithIndex("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("Money", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("househookpointitem")
	t.Static = true
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.AddWithIndex("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("HookpointID", "int(10) unsigned").NotNullable().SetDefault("0")
	t.Add("Heading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("ItemTemplateID", "text")
	t.Add("Index", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 10019
	allTables = append(allTables, *t)

	t = newTable("househookpointoffset")
	t.Static = true
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.Add("HouseModel", "int(11)").NotNullable().SetDefault("0")
	t.Add("HookpointID", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 144
	allTables = append(allTables, *t)

	t = newTable("InstanceXElement")
	t.Static = true
	t.AddWithIndex("InstanceID", "varchar(255)").NotNullable()
	t.Add("ClassType", "text")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("NPCTemplate", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("InstanceXElement_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Inventory")
	t.AddWithIndex("OwnerID", "varchar(255)").NotNullable()
	t.Add("OwnerLot", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.AddWithIndex("ITemplate_Id", "varchar(255)").SetDefault("NULL")
	t.AddWithIndex("UTemplate_Id", "varchar(255)").SetDefault("NULL")
	t.Add("IsCrafted", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Creator", "text")
	t.AddWithIndex("SlotPosition", "int(11)").NotNullable().SetDefault("0")
	t.Add("Count", "int(11)").NotNullable().SetDefault("0")
	t.Add("SellPrice", "int(11)").NotNullable().SetDefault("0")
	t.Add("Experience", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("Extension", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Condition", "int(11)").NotNullable().SetDefault("0")
	t.Add("Durability", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonMaxCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Cooldown", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Inventory_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ItemTemplate")
	t.Static = true
	t.AddPrimary("Id_nb", "varchar(255)").NotNullable()
	t.Add("TranslationId", "text")
	t.Add("Name", "text").NotNullable()
	t.Add("ExamineArticle", "text")
	t.Add("MessageArticle", "text")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("Durability", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxDurability", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsNotLosingDur", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Condition", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCondition", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quality", "int(11)").NotNullable().SetDefault("0")
	t.Add("DPS_AF", "int(11)").NotNullable().SetDefault("0")
	t.Add("SPD_ABS", "int(11)").NotNullable().SetDefault("0")
	t.Add("Hand", "int(11)").NotNullable().SetDefault("0")
	t.Add("Type_Damage", "int(11)").NotNullable().SetDefault("0")
	t.Add("Object_Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Item_Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("Effect", "int(11)").NotNullable().SetDefault("0")
	t.Add("Weight", "int(11)").NotNullable().SetDefault("0")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Extension", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Bonus", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus2", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus3", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus4", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus5", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus6", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus7", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus8", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus9", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus10", "int(11)").NotNullable().SetDefault("0")
	t.Add("ExtraBonus", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus1Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus2Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus3Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus4Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus5Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus6Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus7Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus8Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus9Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus10Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("ExtraBonusType", "int(11)").NotNullable().SetDefault("0")
	t.Add("CanUseEvery", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpellID1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges1", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCharges1", "int(11)").NotNullable().SetDefault("0")
	t.Add("ProcChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ProcSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ProcSpellID1", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonMaxCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsPickable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsDropable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CanDropAsLoot", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsTradable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Price", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MaxCount", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsIndestructible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("PackSize", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("AllowedClasses", "text").NotNullable()
	t.Add("Flags", "int(11)").NotNullable().SetDefault("0")
	t.Add("BonusLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("LevelRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("Description", "text")
	t.Add("ClassType", "varchar(255)").SetDefault("NULL")
	t.Add("SalvageYieldID", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("ItemTemplate_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("ItemUnique")
	t.Static = true
	t.AddPrimary("Id_nb", "varchar(255)").NotNullable()
	t.Add("TranslationId", "text")
	t.Add("Name", "text").NotNullable()
	t.Add("ExamineArticle", "text")
	t.Add("MessageArticle", "text")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("Durability", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxDurability", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsNotLosingDur", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Condition", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCondition", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quality", "int(11)").NotNullable().SetDefault("0")
	t.Add("DPS_AF", "int(11)").NotNullable().SetDefault("0")
	t.Add("SPD_ABS", "int(11)").NotNullable().SetDefault("0")
	t.Add("Hand", "int(11)").NotNullable().SetDefault("0")
	t.Add("Type_Damage", "int(11)").NotNullable().SetDefault("0")
	t.Add("Object_Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Item_Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("Effect", "int(11)").NotNullable().SetDefault("0")
	t.Add("Weight", "int(11)").NotNullable().SetDefault("0")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Extension", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Bonus", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus2", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus3", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus4", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus5", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus6", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus7", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus8", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus9", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus10", "int(11)").NotNullable().SetDefault("0")
	t.Add("ExtraBonus", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus1Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus2Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus3Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus4Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus5Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus6Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus7Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus8Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus9Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bonus10Type", "int(11)").NotNullable().SetDefault("0")
	t.Add("ExtraBonusType", "int(11)").NotNullable().SetDefault("0")
	t.Add("CanUseEvery", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpellID1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charges1", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxCharges1", "int(11)").NotNullable().SetDefault("0")
	t.Add("ProcChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ProcSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ProcSpellID1", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("PoisonMaxCharges", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsPickable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsDropable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("CanDropAsLoot", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsTradable", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Price", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MaxCount", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsIndestructible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("PackSize", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("AllowedClasses", "text").NotNullable()
	t.Add("Flags", "int(11)").NotNullable().SetDefault("0")
	t.Add("BonusLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("LevelRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("Description", "text")
	t.Add("ClassType", "varchar(255)").SetDefault("NULL")
	t.Add("SalvageYieldID", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("ItemUnique_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("KeepCaptureLog")
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.Add("DateTaken", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("KeepName", "text").NotNullable()
	t.Add("KeepType", "text").NotNullable()
	t.Add("NumEnemies", "int(11)").NotNullable().SetDefault("0")
	t.Add("CombatTime", "int(11)").NotNullable().SetDefault("0")
	t.Add("RPReward", "int(11)").NotNullable().SetDefault("0")
	t.Add("BPReward", "int(11)").NotNullable().SetDefault("0")
	t.Add("XPReward", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("MoneyReward", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("CapturedBy", "text").NotNullable()
	t.Add("RPGainerList", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("KeepComponent")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("Health", "int(11)").NotNullable().SetDefault("0")
	t.Add("Skin", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("KeepID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("ID", "int(11)").NotNullable().SetDefault("0")
	t.Add("CreateInfo", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("KeepComponent_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("KeepHookPointItem")
	t.AddWithIndex("KeepID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("ComponentID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("HookPointID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassType", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("KeepHookPointItem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("KeepHookPoint")
	t.AddWithIndex("HookPointID", "int(11)").NotNullable().SetDefault("0")
	t.Add("KeepComponentSkinID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("Height", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("KeepHookPoint_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("KeepPosition")
	t.Static = true
	t.AddWithIndex("ComponentSkin", "int(11)").NotNullable().SetDefault("0")
	t.Add("ComponentRotation", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("TemplateID", "varchar(255)").NotNullable()
	t.AddWithIndex("Height", "int(11)").NotNullable().SetDefault("0")
	t.Add("XOff", "int(11)").NotNullable().SetDefault("0")
	t.Add("YOff", "int(11)").NotNullable().SetDefault("0")
	t.Add("ZOff", "int(11)").NotNullable().SetDefault("0")
	t.Add("HOff", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("ClassType", "varchar(255)").SetDefault("NULL")
	t.Add("TemplateType", "int(11)").NotNullable().SetDefault("0")
	t.Add("KeepType", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("KeepPosition_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Keep")
	t.Static = true
	t.AddPrimary("KeepID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Name", "text").NotNullable()
	t.Add("Region", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Level", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ClaimedGuildName", "text")
	t.Add("AlbionDifficultyLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MidgardDifficultyLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("HiberniaDifficultyLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("OriginalRealm", "int(11)").NotNullable().SetDefault("0")
	t.Add("KeepType", "int(11)").NotNullable().SetDefault("0")
	t.Add("BaseLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("SkinType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("CreateInfo", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Keep_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("LanguageArea")
	t.Static = true
	t.Add("Description", "text").NotNullable()
	t.Add("ScreenDescription", "text").NotNullable()
	t.AddWithIndex("TranslationId", "varchar(255)").NotNullable()
	t.AddWithIndex("Language", "varchar(255)").NotNullable()
	t.Add("Tag", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LanguageArea_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LanguageGameObject")
	t.Static = true
	t.Add("Name", "text")
	t.Add("ExamineArticle", "text")
	t.AddWithIndex("TranslationId", "varchar(255)").NotNullable()
	t.AddWithIndex("Language", "varchar(255)").NotNullable()
	t.Add("Tag", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LanguageGameObject_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LanguageNPC")
	t.Static = true
	t.Add("Name", "text")
	t.Add("Suffix", "text")
	t.Add("GuildName", "text")
	t.Add("ExamineArticle", "text")
	t.Add("MessageArticle", "text")
	t.AddWithIndex("TranslationId", "varchar(255)").NotNullable()
	t.AddWithIndex("Language", "varchar(255)").NotNullable()
	t.Add("Tag", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LanguageNPC_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LanguageSystem")
	t.Static = true
	t.Add("Text", "text").NotNullable()
	t.AddWithIndex("TranslationId", "varchar(255)").NotNullable()
	t.AddWithIndex("Language", "varchar(255)").NotNullable()
	t.Add("Tag", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LanguageSystem_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LanguageZone")
	t.Static = true
	t.Add("Description", "text").NotNullable()
	t.Add("ScreenDescription", "text").NotNullable()
	t.AddWithIndex("TranslationId", "varchar(255)").NotNullable()
	t.AddWithIndex("Language", "varchar(255)").NotNullable()
	t.Add("Tag", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LanguageZone_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LineXSpell")
	t.Static = true
	t.AddWithIndex("LineName", "varchar(255)").NotNullable()
	t.Add("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LineXSpell_ID", "varchar(255)").NotNullable()
	t.Add("PackageID", "text")
	allTables = append(allTables, *t)

	t = newTable("LinkedFaction")
	t.Static = true
	t.Add("FactionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("LinkedFactionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsFriend", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LinkedFaction_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LootGenerator")
	t.Static = true
	t.Add("MobName", "text")
	t.Add("MobGuild", "text")
	t.Add("MobFaction", "text")
	t.Add("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("LootGeneratorClass", "text").NotNullable()
	t.Add("ExclusivePriority", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LootGenerator_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LootOTD")
	t.Static = true
	t.AddWithIndex("MobName", "varchar(100)").NotNullable()
	t.AddWithIndex("ItemTemplateID", "varchar(100)").NotNullable()
	t.Add("MinLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LootOTD_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("LootTemplate")
	t.Static = true
	t.AddWithIndex("TemplateName", "varchar(255)").NotNullable()
	t.Add("ItemTemplateID", "text").NotNullable()
	t.Add("Chance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Count", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("LootTemplate_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("MerchantItem")
	t.Static = true
	t.AddWithIndex("ItemListID", "varchar(255)").NotNullable()
	t.Add("ItemTemplateID", "text").NotNullable()
	t.AddWithIndex("PageNumber", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("SlotPosition", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("MerchantItem_ID", "varchar(255)").NotNullable()
	t.Add("Price", "bigint(20)").SetDefault("0")
	allTables = append(allTables, *t)

	t = newTable("Minotaurrelic")
	t.Static = true
	t.Add("relicSpell", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpawnLocked", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ProtectorClassType", "text").NotNullable()
	t.Add("relicTarget", "text").NotNullable()
	t.Add("Name", "text").NotNullable()
	t.Add("Model", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("SpawnX", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpawnY", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpawnZ", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpawnHeading", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpawnRegion", "int(11)").NotNullable().SetDefault("0")
	t.Add("Effect", "int(11)").NotNullable().SetDefault("0")
	t.AddPrimary("RelicID", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Minotaurrelic_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("MobDropTemplate")
	t.Static = true
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.AddWithIndex("MobName", "varchar(255)").NotNullable()
	t.AddWithIndex("LootTemplateName", "varchar(255)").NotNullable()
	t.Add("DropCount", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("Mob")
	t.Static = true
	t.Add("ClassType", "text")
	t.Add("TranslationId", "text")
	t.AddWithIndex("Name", "varchar(255)").NotNullable()
	t.Add("Suffix", "text")
	t.Add("Guild", "text")
	t.Add("ExamineArticle", "text")
	t.Add("MessageArticle", "text")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Speed", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Region", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Model", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Size", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Strength", "int(11)").NotNullable().SetDefault("0")
	t.Add("Constitution", "int(11)").NotNullable().SetDefault("0")
	t.Add("Dexterity", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quickness", "int(11)").NotNullable().SetDefault("0")
	t.Add("Intelligence", "int(11)").NotNullable().SetDefault("0")
	t.Add("Piety", "int(11)").NotNullable().SetDefault("0")
	t.Add("Empathy", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charisma", "int(11)").NotNullable().SetDefault("0")
	t.Add("Level", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EquipmentTemplateID", "text")
	t.Add("ItemsListTemplateID", "text")
	t.Add("NPCTemplateID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Race", "int(11)").NotNullable().SetDefault("0")
	t.Add("Flags", "int(10) unsigned").NotNullable().SetDefault("0")
	t.Add("AggroLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("AggroRange", "int(11)").NotNullable().SetDefault("0")
	t.Add("MeleeDamageType", "int(11)").NotNullable().SetDefault("0")
	t.Add("RespawnInterval", "int(11)").NotNullable().SetDefault("0")
	t.Add("FactionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("BodyType", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("HouseNumber", "int(11)").NotNullable().SetDefault("0")
	t.Add("Brain", "text")
	t.Add("PathID", "text")
	t.Add("MaxDistance", "int(11)").NotNullable().SetDefault("0")
	t.Add("OwnerID", "varchar(255)").NotNullable()
	t.Add("RoamingRange", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsCloakHoodUp", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Gender", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("VisibleWeaponSlots", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Mob_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("MobXAmbientBehaviour")
	t.Static = true
	t.AddWithIndex("Source", "varchar(255)").NotNullable()
	t.Add("Trigger", "text").NotNullable()
	t.Add("Emote", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Text", "text").NotNullable()
	t.Add("Chance", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Voice", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("MobXAmbientBehaviour_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("MobXLootTemplate")
	t.Static = true
	t.AddWithIndex("MobName", "varchar(255)").NotNullable()
	t.AddWithIndex("LootTemplateName", "varchar(255)").NotNullable()
	t.Add("DropCount", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("MobXLootTemplate_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("News")
	t.Add("CreationDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("Type", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Text", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("News_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("NPCEquipment")
	t.Static = true
	t.AddWithIndex("TemplateID", "varchar(255)").NotNullable()
	t.Add("Slot", "int(11)").NotNullable().SetDefault("0")
	t.Add("Model", "int(11)").NotNullable().SetDefault("0")
	t.Add("Color", "int(11)").NotNullable().SetDefault("0")
	t.Add("Effect", "int(11)").NotNullable().SetDefault("0")
	t.Add("Extension", "int(11)").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("NPCEquipment_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("NpcTemplate")
	t.Static = true
	t.AddWithIndex("TemplateId", "int(11)").NotNullable().SetDefault("0")
	t.Add("TranslationId", "text")
	t.Add("Name", "text").NotNullable()
	t.Add("Suffix", "text")
	t.Add("ClassType", "text").NotNullable()
	t.Add("GuildName", "text")
	t.Add("ExamineArticle", "text")
	t.Add("MessageArticle", "text")
	t.Add("Model", "text").NotNullable()
	t.Add("Gender", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Size", "text").NotNullable()
	t.Add("Level", "text").NotNullable()
	t.Add("MaxSpeed", "smallint(6)").NotNullable().SetDefault("0")
	t.Add("EquipmentTemplateID", "text")
	t.Add("ItemsListTemplateID", "text")
	t.Add("Flags", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("MeleeDamageType", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ParryChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("EvadeChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("BlockChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LeftHandSwingChance", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("Spells", "text")
	t.Add("Styles", "text")
	t.Add("Strength", "int(11)").NotNullable().SetDefault("0")
	t.Add("Constitution", "int(11)").NotNullable().SetDefault("0")
	t.Add("Dexterity", "int(11)").NotNullable().SetDefault("0")
	t.Add("Quickness", "int(11)").NotNullable().SetDefault("0")
	t.Add("Intelligence", "int(11)").NotNullable().SetDefault("0")
	t.Add("Piety", "int(11)").NotNullable().SetDefault("0")
	t.Add("Charisma", "int(11)").NotNullable().SetDefault("0")
	t.Add("Empathy", "int(11)").NotNullable().SetDefault("0")
	t.Add("Abilities", "text")
	t.Add("AggroLevel", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("AggroRange", "int(11)").NotNullable().SetDefault("0")
	t.Add("Race", "int(11)").NotNullable().SetDefault("0")
	t.Add("BodyType", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxDistance", "int(11)").NotNullable().SetDefault("0")
	t.Add("TetherRange", "int(11)").NotNullable().SetDefault("0")
	t.Add("VisibleWeaponSlots", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("ReplaceMobValues", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("NpcTemplate_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("PathPoints")
	t.Static = true
	t.AddWithIndex("PathID", "varchar(255)").NotNullable()
	t.Add("Step", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaxSpeed", "int(11)").NotNullable().SetDefault("0")
	t.Add("WaitTime", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("PathPoints_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Path")
	t.Static = true
	t.AddUnique("PathID", "varchar(255)").NotNullable()
	t.Add("PathType", "int(11)").NotNullable().SetDefault("0")
	t.Add("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Path_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("PlayerBoats")
	t.Add("BoatID", "text").NotNullable()
	t.Add("BoatOwner", "text").NotNullable()
	t.AddPrimary("BoatName", "varchar(255)").NotNullable()
	t.Add("BoatModel", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("BoatMaxSpeedBase", "smallint(6)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("PlayerBoats_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("PlayerInfo")
	t.Add("Name", "text")
	t.Add("LastName", "text")
	t.Add("Guild", "text")
	t.Add("Race", "text")
	t.Add("Class", "text")
	t.Add("Alive", "text")
	t.Add("Realm", "text")
	t.Add("Region", "text")
	t.Add("Level", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("PlayerInfo_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("PlayerXEffect")
	t.Add("IsHandler", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Var6", "int(11)").NotNullable().SetDefault("0")
	t.Add("Var5", "int(11)").NotNullable().SetDefault("0")
	t.Add("Var4", "int(11)").NotNullable().SetDefault("0")
	t.Add("Var3", "int(11)").NotNullable().SetDefault("0")
	t.Add("Var2", "int(11)").NotNullable().SetDefault("0")
	t.Add("Var1", "int(11)").NotNullable().SetDefault("0")
	t.Add("Duration", "int(11)").NotNullable().SetDefault("0")
	t.Add("EffectType", "text")
	t.Add("SpellLine", "text")
	t.AddWithIndex("ChardID", "varchar(255)").SetDefault("NULL")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("PlayerXEffect_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("PvPKillsLog")
	t.AddPrimary("ID", "bigint(20)").NotNullable()
	t.Add("DateKilled", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("KilledName", "text").NotNullable()
	t.Add("KillerName", "text").NotNullable()
	t.Add("KillerIP", "text").NotNullable()
	t.Add("KilledIP", "text").NotNullable()
	t.Add("KilledRealm", "text").NotNullable()
	t.Add("KillerRealm", "text").NotNullable()
	t.Add("RPReward", "int(11)").NotNullable().SetDefault("0")
	t.Add("SameIP", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("RegionName", "text")
	t.Add("IsInstance", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("Quest")
	t.Static = true
	t.Add("Name", "text").NotNullable()
	t.Add("Step", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("Character_ID", "varchar(255)").NotNullable()
	t.Add("CustomPropertiesString", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Quest_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Race")
	t.Static = true
	t.AddUnique("ID", "int(11)").NotNullable().SetDefault("0")
	t.AddUnique("Name", "varchar(255)").NotNullable()
	t.Add("ResistBody", "tinyint(3)").NotNullable()
	t.Add("ResistCold", "tinyint(3)").NotNullable()
	t.Add("ResistCrush", "tinyint(3)").NotNullable()
	t.Add("ResistEnergy", "tinyint(3)").NotNullable()
	t.Add("ResistHeat", "tinyint(3)").NotNullable()
	t.Add("ResistMatter", "tinyint(3)").NotNullable()
	t.Add("ResistNatural", "tinyint(3)").NotNullable()
	t.Add("ResistSlash", "tinyint(3)").NotNullable()
	t.Add("ResistSpirit", "tinyint(3)").NotNullable()
	t.Add("ResistThrust", "tinyint(3)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Race_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Regions")
	t.Static = true
	t.AddPrimary("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Name", "text").NotNullable()
	t.Add("Description", "text").NotNullable()
	t.Add("IP", "text").NotNullable()
	t.Add("Port", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Expansion", "int(11)").NotNullable().SetDefault("0")
	t.Add("HousingEnabled", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("DivingEnabled", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("WaterLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassType", "varchar(200)").NotNullable()
	t.Add("IsFrontier", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Regions_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("Relic")
	t.AddPrimary("RelicID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Region", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("OriginalRealm", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastRealm", "int(11)").NotNullable().SetDefault("0")
	t.Add("relicType", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Relic_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("Salvage")
	t.Static = true
	t.AddWithIndex("ObjectType", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("SalvageLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("Id_nb", "text").NotNullable()
	t.AddWithIndex("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Salvage_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("SalvageYield")
	t.Static = true
	t.AddPrimary("ID", "int(11)").NotNullable()
	t.AddWithIndex("ObjectType", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("SalvageLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("MaterialId_nb", "text").NotNullable()
	t.Add("Count", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 366
	allTables = append(allTables, *t)

	t = newTable("ServerInfo")
	t.Add("Time", "text")
	t.Add("ServerName", "text")
	t.Add("AAC", "text")
	t.Add("ServerType", "text")
	t.Add("ServerStatus", "text")
	t.Add("NumClients", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumAccounts", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumMobs", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumInventoryItems", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumPlayerChars", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumMerchantItems", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumItemTemplates", "int(11)").NotNullable().SetDefault("0")
	t.Add("NumWorldObjects", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("ServerInfo_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("serverproperty_category")
	t.Add("BaseCategory", "text").NotNullable()
	t.Add("ParentCategory", "text")
	t.Add("DisplayName", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("serverproperty_category_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ServerProperty")
	t.Add("Category", "text").NotNullable()
	t.AddPrimary("Key", "varchar(255)").NotNullable()
	t.Add("Description", "text").NotNullable()
	t.Add("DefaultValue", "text").NotNullable()
	t.Add("Value", "text").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("ServerProperty_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("serverstats")
	t.Add("StatDate", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.Add("Clients", "int(11)").NotNullable().SetDefault("0")
	t.Add("CPU", "double").NotNullable()
	t.Add("Upload", "int(11)").NotNullable().SetDefault("0")
	t.Add("Download", "int(11)").NotNullable().SetDefault("0")
	t.Add("Memory", "bigint(20)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("serverstats_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("SinglePermission")
	t.AddWithIndex("PlayerID", "varchar(255)").NotNullable()
	t.AddWithIndex("Command", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("SinglePermission_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Specialization")
	t.Static = true
	t.AddPrimary("SpecializationID", "int(11)").NotNullable()
	t.AddUnique("KeyName", "varchar(100)").NotNullable()
	t.Add("Name", "varchar(255)").NotNullable()
	t.Add("Icon", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Description", "text")
	t.Add("Implementation", "varchar(255)").SetDefault("NULL")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 225
	allTables = append(allTables, *t)

	t = newTable("SpecXAbility")
	t.Static = true
	t.AddPrimary("SpecXabilityID", "int(11)").NotNullable()
	t.AddWithIndex("Spec", "varchar(100)").NotNullable()
	t.Add("SpecLevel", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("AbilityKey", "varchar(100)").NotNullable()
	t.Add("AbilityLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassId", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 367
	allTables = append(allTables, *t)

	t = newTable("SpellLine")
	t.Static = true
	t.AddPrimary("SpellLineID", "int(11)").NotNullable()
	t.AddUnique("KeyName", "varchar(255)").NotNullable()
	t.Add("Name", "varchar(255)").SetDefault("NULL")
	t.AddWithIndex("Spec", "varchar(100)").SetDefault("NULL")
	t.Add("IsBaseLine", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ClassIDHint", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1463
	allTables = append(allTables, *t)

	t = newTable("Spell")
	t.Static = true
	t.AddUnique("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClientEffect", "int(11)").NotNullable().SetDefault("0")
	t.Add("Icon", "int(11)").NotNullable().SetDefault("0")
	t.Add("Name", "text").NotNullable()
	t.Add("Description", "text").NotNullable()
	t.Add("Target", "text").NotNullable()
	t.Add("Range", "int(11)").NotNullable().SetDefault("0")
	t.Add("Power", "int(11)").NotNullable().SetDefault("0")
	t.Add("CastTime", "double").NotNullable().SetDefault("0")
	t.Add("Damage", "double").NotNullable().SetDefault("0")
	t.Add("DamageType", "int(11)").NotNullable().SetDefault("0")
	t.Add("Type", "text")
	t.Add("Duration", "int(11)").NotNullable().SetDefault("0")
	t.Add("Frequency", "int(11)").NotNullable().SetDefault("0")
	t.Add("Pulse", "int(11)").NotNullable().SetDefault("0")
	t.Add("PulsePower", "int(11)").NotNullable().SetDefault("0")
	t.Add("Radius", "int(11)").NotNullable().SetDefault("0")
	t.Add("RecastDelay", "int(11)").NotNullable().SetDefault("0")
	t.Add("ResurrectHealth", "int(11)").NotNullable().SetDefault("0")
	t.Add("ResurrectMana", "int(11)").NotNullable().SetDefault("0")
	t.Add("Value", "double").NotNullable().SetDefault("0")
	t.Add("Concentration", "int(11)").NotNullable().SetDefault("0")
	t.Add("LifeDrainReturn", "int(11)").NotNullable().SetDefault("0")
	t.Add("AmnesiaChance", "int(11)").NotNullable().SetDefault("0")
	t.Add("Message1", "text")
	t.Add("Message2", "text")
	t.Add("Message3", "text")
	t.Add("Message4", "text")
	t.Add("InstrumentRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("SpellGroup", "int(11)").NotNullable().SetDefault("0")
	t.Add("EffectGroup", "int(11)").NotNullable().SetDefault("0")
	t.Add("SubSpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("MoveCast", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("Uninterruptible", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsFocus", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("SharedTimerGroup", "int(11)").NotNullable().SetDefault("0")
	t.Add("IsPrimary", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("IsSecondary", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("AllowBolt", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("PackageID", "text")
	t.Add("TooltipId", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Spell_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("SpellXCustomValues")
	t.AddWithIndex("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("KeyName", "varchar(100)").NotNullable()
	t.Add("Value", "varchar(255)").SetDefault("NULL")
	t.AddPrimary("CustomParamID", "int(11)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 1
	allTables = append(allTables, *t)

	t = newTable("StarterEquipment")
	t.Static = true
	t.AddPrimary("StarterEquipmentID", "int(11)").NotNullable()
	t.Add("Class", "text").NotNullable()
	t.Add("TemplateID", "varchar(255)").NotNullable()
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 128
	allTables = append(allTables, *t)

	t = newTable("StartupLocation")
	t.Static = true
	t.AddPrimary("StartupLoc_ID", "int(11)").NotNullable()
	t.Add("XPos", "int(11)").NotNullable().SetDefault("0")
	t.Add("YPos", "int(11)").NotNullable().SetDefault("0")
	t.Add("ZPos", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("Region", "int(11)").NotNullable().SetDefault("0")
	t.Add("MinVersion", "int(11)").NotNullable().SetDefault("0")
	t.Add("RealmID", "int(11)").NotNullable().SetDefault("0")
	t.Add("RaceID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClientRegionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 137
	allTables = append(allTables, *t)

	t = newTable("Style")
	t.Static = true
	t.AddPrimary("StyleID", "int(11)").NotNullable()
	t.Add("ID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassId", "int(11)").NotNullable().SetDefault("0")
	t.Add("Name", "varchar(255)").NotNullable()
	t.AddWithIndex("SpecKeyName", "varchar(100)").NotNullable()
	t.Add("SpecLevelRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("Icon", "int(11)").NotNullable().SetDefault("0")
	t.Add("EnduranceCost", "int(11)").NotNullable().SetDefault("0")
	t.Add("StealthRequirement", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("OpeningRequirementType", "int(11)").NotNullable().SetDefault("0")
	t.Add("OpeningRequirementValue", "int(11)").NotNullable().SetDefault("0")
	t.Add("AttackResultRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("WeaponTypeRequirement", "int(11)").NotNullable().SetDefault("0")
	t.Add("GrowthOffset", "double").NotNullable().SetDefault("0")
	t.Add("GrowthRate", "double").NotNullable().SetDefault("0")
	t.Add("BonusToHit", "int(11)").NotNullable().SetDefault("0")
	t.Add("BonusToDefense", "int(11)").NotNullable().SetDefault("0")
	t.Add("TwoHandAnimation", "int(11)").NotNullable().SetDefault("0")
	t.Add("RandomProc", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("ArmorHitLocation", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AutoIncrement = 50014
	allTables = append(allTables, *t)

	t = newTable("StyleXSpell")
	t.Static = true
	t.Add("SpellID", "int(11)").NotNullable().SetDefault("0")
	t.Add("ClassID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("StyleID", "int(11)").NotNullable().SetDefault("0")
	t.Add("Chance", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("StyleXSpell_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Task")
	t.AddPrimary("Character_ID", "varchar(255)").NotNullable()
	t.Add("TimeOut", "datetime").SetDefault("NULL")
	t.Add("TaskType", "text")
	t.Add("TasksDone", "int(11)").NotNullable().SetDefault("0")
	t.Add("CustomPropertiesString", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Task_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("Teleport")
	t.Static = true
	t.Add("Type", "text").NotNullable()
	t.AddWithIndex("TeleportID", "varchar(255)").NotNullable()
	t.Add("Realm", "int(11)").NotNullable().SetDefault("0")
	t.Add("RegionID", "int(11)").NotNullable().SetDefault("0")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("Teleport_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("TownCrierMessages")
	t.Static = true
	t.AddPrimary("TownCrierID", "varchar(255)").NotNullable()
	t.Add("Message", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("TownCrierMessages_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	t = newTable("WorldObject")
	t.Static = true
	t.Add("ClassType", "text")
	t.Add("TranslationId", "text")
	t.Add("Name", "text").NotNullable()
	t.Add("ExamineArticle", "text")
	t.Add("X", "int(11)").NotNullable().SetDefault("0")
	t.Add("Y", "int(11)").NotNullable().SetDefault("0")
	t.Add("Z", "int(11)").NotNullable().SetDefault("0")
	t.Add("Heading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.AddWithIndex("Region", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Model", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Emblem", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("RespawnInterval", "int(11)").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("WorldObject_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("ZonePoint")
	t.Static = true
	t.AddWithIndex("Id", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("TargetX", "int(11)").NotNullable().SetDefault("0")
	t.Add("TargetY", "int(11)").NotNullable().SetDefault("0")
	t.Add("TargetZ", "int(11)").NotNullable().SetDefault("0")
	t.Add("TargetRegion", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("TargetHeading", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("SourceX", "int(11)").NotNullable().SetDefault("0")
	t.Add("SourceY", "int(11)").NotNullable().SetDefault("0")
	t.Add("SourceZ", "int(11)").NotNullable().SetDefault("0")
	t.Add("SourceRegion", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.AddWithIndex("Realm", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("ClassType", "text")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddPrimary("ZonePoint_ID", "varchar(255)").NotNullable()
	allTables = append(allTables, *t)

	t = newTable("Zones")
	t.Static = true
	t.AddPrimary("ZoneID", "int(11)").NotNullable().SetDefault("0")
	t.AddWithIndex("RegionID", "smallint(5) unsigned").NotNullable().SetDefault("0")
	t.Add("Name", "text").NotNullable()
	t.Add("IsLava", "tinyint(1)").NotNullable().SetDefault("0")
	t.Add("DivingFlag", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("WaterLevel", "int(11)").NotNullable().SetDefault("0")
	t.Add("OffsetY", "int(11)").NotNullable().SetDefault("0")
	t.Add("OffsetX", "int(11)").NotNullable().SetDefault("0")
	t.Add("Width", "int(11)").NotNullable().SetDefault("0")
	t.Add("Height", "int(11)").NotNullable().SetDefault("0")
	t.Add("Experience", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realmpoints", "int(11)").NotNullable().SetDefault("0")
	t.Add("Bountypoints", "int(11)").NotNullable().SetDefault("0")
	t.Add("Coin", "int(11)").NotNullable().SetDefault("0")
	t.Add("Realm", "tinyint(3) unsigned").NotNullable().SetDefault("0")
	t.Add("LastTimeRowUpdated", "datetime").NotNullable().SetDefault("2000-01-01 00:00:00")
	t.AddUnique("Zones_ID", "varchar(255)").SetDefault("NULL")
	allTables = append(allTables, *t)

	return allTables
}
