DROP TABLE IF EXISTS `househookpointoffset`;

CREATE TABLE `househookpointoffset` (`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`HouseModel` INT(11) NOT NULL DEFAULT 0, 
`HookpointID` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
