CREATE TABLE IF NOT EXISTS `KeepComponent` (`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`Health` INT(11) NOT NULL DEFAULT 0, 
`Skin` INT(11) NOT NULL DEFAULT 0, 
`KeepID` INT(11) NOT NULL DEFAULT 0, 
`ID` INT(11) NOT NULL DEFAULT 0, 
`CreateInfo` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`KeepComponent_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`KeepComponent_ID`));
CREATE INDEX `I_KeepComponent_KeepID` ON `KeepComponent` (`KeepID`);
CREATE INDEX `I_KeepComponent_ID` ON `KeepComponent` (`ID`);
