DROP TABLE IF EXISTS `LootOTD`;

CREATE TABLE `LootOTD` (`MobName` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`ItemTemplateID` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`MinLevel` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`LootOTD_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`LootOTD_ID`));
CREATE INDEX `I_LootOTD_MobName` ON `LootOTD` (`MobName`);
CREATE INDEX `I_LootOTD_ItemTemplateID` ON `LootOTD` (`ItemTemplateID`);
