DROP TABLE IF EXISTS `Minotaurrelic`;

CREATE TABLE `Minotaurrelic` (`relicSpell` INT(11) NOT NULL DEFAULT 0, 
`SpawnLocked` TINYINT(1) NOT NULL DEFAULT 0, 
`ProtectorClassType` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`relicTarget` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Model` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`SpawnX` INT(11) NOT NULL DEFAULT 0, 
`SpawnY` INT(11) NOT NULL DEFAULT 0, 
`SpawnZ` INT(11) NOT NULL DEFAULT 0, 
`SpawnHeading` INT(11) NOT NULL DEFAULT 0, 
`SpawnRegion` INT(11) NOT NULL DEFAULT 0, 
`Effect` INT(11) NOT NULL DEFAULT 0, 
`RelicID` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Minotaurrelic_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`RelicID`));
CREATE UNIQUE INDEX `U_Minotaurrelic_Minotaurrelic_ID` ON `Minotaurrelic` (`Minotaurrelic_ID`);
