DROP TABLE IF EXISTS `PathPoints`;

CREATE TABLE `PathPoints` (`PathID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Step` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`MaxSpeed` INT(11) NOT NULL DEFAULT 0, 
`WaitTime` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`PathPoints_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`PathPoints_ID`));
CREATE INDEX `I_PathPoints_PathID` ON `PathPoints` (`PathID`);
