DROP TABLE IF EXISTS `Quest`;

CREATE TABLE `Quest` (`Name` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`Step` INT(11) NOT NULL DEFAULT 0, 
`Character_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`CustomPropertiesString` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Quest_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Quest_ID`));
CREATE INDEX `I_Quest_Character_ID` ON `Quest` (`Character_ID`);
