CREATE TABLE IF NOT EXISTS `Relic` (`RelicID` INT(11) NOT NULL DEFAULT 0, 
`Region` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`Realm` INT(11) NOT NULL DEFAULT 0, 
`OriginalRealm` INT(11) NOT NULL DEFAULT 0, 
`LastRealm` INT(11) NOT NULL DEFAULT 0, 
`relicType` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Relic_ID` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
PRIMARY KEY (`RelicID`));
CREATE UNIQUE INDEX `U_Relic_Relic_ID` ON `Relic` (`Relic_ID`);
