DROP TABLE IF EXISTS `SpecXAbility`;

CREATE TABLE `SpecXAbility` (`SpecXabilityID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`Spec` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`SpecLevel` INT(11) NOT NULL DEFAULT 0, 
`AbilityKey` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`AbilityLevel` INT(11) NOT NULL DEFAULT 0, 
`ClassId` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE INDEX `I_SpecXAbility_Spec` ON `SpecXAbility` (`Spec`);
CREATE INDEX `I_SpecXAbility_AbilityKey` ON `SpecXAbility` (`AbilityKey`);
