CREATE TABLE IF NOT EXISTS `SpellXCustomValues` (`SpellID` INT(11) NOT NULL DEFAULT 0, 
`KeyName` VARCHAR(100) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Value` VARCHAR(255) DEFAULT NULL COLLATE NOCASE, 
`CustomParamID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
CREATE INDEX `I_SpellXCustomValues_SpellID` ON `SpellXCustomValues` (`SpellID`);
CREATE INDEX `I_SpellXCustomValues_KeyName` ON `SpellXCustomValues` (`KeyName`);
