DROP TABLE IF EXISTS `StartupLocation`;

CREATE TABLE `StartupLocation` (`StartupLoc_ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
`XPos` INT(11) NOT NULL DEFAULT 0, 
`YPos` INT(11) NOT NULL DEFAULT 0, 
`ZPos` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`Region` INT(11) NOT NULL DEFAULT 0, 
`MinVersion` INT(11) NOT NULL DEFAULT 0, 
`RealmID` INT(11) NOT NULL DEFAULT 0, 
`RaceID` INT(11) NOT NULL DEFAULT 0, 
`ClassID` INT(11) NOT NULL DEFAULT 0, 
`ClientRegionID` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00');
