DROP TABLE IF EXISTS `Teleport`;

CREATE TABLE `Teleport` (`Type` TEXT NOT NULL DEFAULT '' COLLATE NOCASE, 
`TeleportID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
`Realm` INT(11) NOT NULL DEFAULT 0, 
`RegionID` INT(11) NOT NULL DEFAULT 0, 
`X` INT(11) NOT NULL DEFAULT 0, 
`Y` INT(11) NOT NULL DEFAULT 0, 
`Z` INT(11) NOT NULL DEFAULT 0, 
`Heading` INT(11) NOT NULL DEFAULT 0, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`Teleport_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`Teleport_ID`));
CREATE INDEX `I_Teleport_TeleportID` ON `Teleport` (`TeleportID`);
