DROP TABLE IF EXISTS `ZonePoint`;

CREATE TABLE `ZonePoint` (`Id` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`TargetX` INT(11) NOT NULL DEFAULT 0, 
`TargetY` INT(11) NOT NULL DEFAULT 0, 
`TargetZ` INT(11) NOT NULL DEFAULT 0, 
`TargetRegion` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`TargetHeading` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`SourceX` INT(11) NOT NULL DEFAULT 0, 
`SourceY` INT(11) NOT NULL DEFAULT 0, 
`SourceZ` INT(11) NOT NULL DEFAULT 0, 
`SourceRegion` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`Realm` UNSIGNED SMALLINT(5) NOT NULL DEFAULT 0, 
`ClassType` TEXT DEFAULT NULL COLLATE NOCASE, 
`LastTimeRowUpdated` DATETIME NOT NULL DEFAULT '2000-01-01 00:00:00', 
`ZonePoint_ID` VARCHAR(255) NOT NULL DEFAULT '' COLLATE NOCASE, 
PRIMARY KEY (`ZonePoint_ID`));
CREATE INDEX `I_ZonePoint_Id` ON `ZonePoint` (`Id`);
CREATE INDEX `I_ZonePoint_Realm` ON `ZonePoint` (`Realm`);
