DROP TABLE IF EXISTS `Mob`;

CREATE TABLE `Mob` (
  `ClassType` text,
  `TranslationId` text,
  `Name` varchar(255) NOT NULL,
  `Suffix` text,
  `Guild` text,
  `ExamineArticle` text,
  `MessageArticle` text,
  `X` int(11) NOT NULL DEFAULT '0',
  `Y` int(11) NOT NULL DEFAULT '0',
  `Z` int(11) NOT NULL DEFAULT '0',
  `Speed` int(11) NOT NULL DEFAULT '0',
  `Heading` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Region` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Model` smallint(5) unsigned NOT NULL DEFAULT '0',
  `Size` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Strength` int(11) NOT NULL DEFAULT '0',
  `Constitution` int(11) NOT NULL DEFAULT '0',
  `Dexterity` int(11) NOT NULL DEFAULT '0',
  `Quickness` int(11) NOT NULL DEFAULT '0',
  `Intelligence` int(11) NOT NULL DEFAULT '0',
  `Piety` int(11) NOT NULL DEFAULT '0',
  `Empathy` int(11) NOT NULL DEFAULT '0',
  `Charisma` int(11) NOT NULL DEFAULT '0',
  `Level` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Realm` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `EquipmentTemplateID` text,
  `ItemsListTemplateID` text,
  `NPCTemplateID` int(11) NOT NULL DEFAULT '0',
  `Race` int(11) NOT NULL DEFAULT '0',
  `Flags` int(10) unsigned NOT NULL DEFAULT '0',
  `AggroLevel` int(11) NOT NULL DEFAULT '0',
  `AggroRange` int(11) NOT NULL DEFAULT '0',
  `MeleeDamageType` int(11) NOT NULL DEFAULT '0',
  `RespawnInterval` int(11) NOT NULL DEFAULT '0',
  `FactionID` int(11) NOT NULL DEFAULT '0',
  `BodyType` int(11) NOT NULL DEFAULT '0',
  `HouseNumber` int(11) NOT NULL DEFAULT '0',
  `Brain` text,
  `PathID` text,
  `MaxDistance` int(11) NOT NULL DEFAULT '0',
  `OwnerID` varchar(255) NOT NULL,
  `RoamingRange` int(11) NOT NULL DEFAULT '0',
  `IsCloakHoodUp` tinyint(1) NOT NULL DEFAULT '0',
  `Gender` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `PackageID` text,
  `VisibleWeaponSlots` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `Mob_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`Mob_ID`),
  KEY `I_Mob_Name` (`Name`),
  KEY `I_Mob_HouseNumber` (`HouseNumber`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
