db:
    host:     localhost
    user:     dol
    password: dol
    database: dol
    port:     3306
exportignore:
    - Appeal
    - AutoXMLUpdate
    - AuditEntry
    - Ban
    - DBHouseCharsXPerms
    - DOLCharacters
    - DBHousePermissions
    - DOLCharactersBackup
    - DOLCharactersBackupXCustomParam
    - DOLCharactersXCustomParam
    - GuildAlliance
    - HouseConsignmentMerchant
    - KeepCaptureLog
    - KeepComponent
    - KeepHookPoint
    - KeepHookPointItem
    - News
    - PlayerXEffect
    - PvPKillsLog
    - ServerInfo
    - serverproperty_category
    - serverstats
    - SinglePermission
    - Task
    - Account
    - CharacterXDataQuest
    - CharacterXMasterLevel
    - CharacterXOneTimeDrop
    - Inventory
    - playerboats
    - playerinfo
    - BugReport
    - Guild
    - GuildRank
    - ServerProperty
    - DBIndoorItem
    - DBOutdoorItem
    - DBHousepermissions
    - DBHousecharxperms
    - DBHouse
    - Relic
    - SpellXCustomValues
    - Task
