/*Table structure for table `dbhouse` */

DROP TABLE IF EXISTS `dbhouse`;

CREATE TABLE `dbhouse` (
  `HouseNumber` int(11) NOT NULL,
  `X` int(11) NOT NULL,
  `Y` int(11) NOT NULL,
  `Z` int(11) NOT NULL,
  `RegionID` smallint(5) unsigned NOT NULL,
  `Heading` int(11) NOT NULL,
  `CreationTime` datetime DEFAULT NULL,
  `Name` text,
  `Model` int(11) DEFAULT NULL,
  `Emblem` int(11) DEFAULT NULL,
  `PorchRoofColor` int(11) DEFAULT NULL,
  `PorchMaterial` int(11) DEFAULT NULL,
  `RoofMaterial` int(11) DEFAULT NULL,
  `DoorMaterial` int(11) DEFAULT NULL,
  `WallMaterial` int(11) DEFAULT NULL,
  `TrussMaterial` int(11) DEFAULT NULL,
  `WindowMaterial` int(11) DEFAULT NULL,
  `Rug1Color` int(11) DEFAULT NULL,
  `Rug2Color` int(11) DEFAULT NULL,
  `Rug3Color` int(11) DEFAULT NULL,
  `Rug4Color` int(11) DEFAULT NULL,
  `IndoorGuildBanner` tinyint(1) DEFAULT NULL,
  `IndoorGuildShield` tinyint(1) DEFAULT NULL,
  `OutdoorGuildBanner` tinyint(1) DEFAULT NULL,
  `OutdoorGuildShield` tinyint(1) DEFAULT NULL,
  `Porch` tinyint(1) DEFAULT NULL,
  `OwnerID` text,
  `LastPaid` datetime DEFAULT NULL,
  `KeptMoney` bigint(20) DEFAULT NULL,
  `NoPurge` tinyint(1) DEFAULT NULL,
  `GuildHouse` tinyint(1) DEFAULT NULL,
  `GuildName` text,
  `HasConsignment` tinyint(1) DEFAULT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `DBHouse_ID` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`HouseNumber`),
  UNIQUE KEY `U_DBHouse_DBHouse_ID` (`DBHouse_ID`),
  KEY `I_DBHouse_RegionID` (`RegionID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
