/*Table structure for table `dolcharactersbackup` */

DROP TABLE IF EXISTS `dolcharactersbackup`;

CREATE TABLE `dolcharactersbackup` (
  `DOLCharacters_ID` varchar(255) NOT NULL,
  `Name` varchar(255) NOT NULL,
  `DeleteDate` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `HasGravestone` tinyint(1) DEFAULT NULL,
  `GravestoneRegion` int(11) DEFAULT NULL,
  `Constitution` int(11) DEFAULT NULL,
  `Dexterity` int(11) DEFAULT NULL,
  `Strength` int(11) DEFAULT NULL,
  `Quickness` int(11) DEFAULT NULL,
  `Intelligence` int(11) DEFAULT NULL,
  `Piety` int(11) DEFAULT NULL,
  `Empathy` int(11) DEFAULT NULL,
  `Charisma` int(11) DEFAULT NULL,
  `BountyPoints` bigint(20) DEFAULT NULL,
  `RealmPoints` bigint(20) DEFAULT NULL,
  `RealmLevel` int(11) DEFAULT NULL,
  `Experience` bigint(20) DEFAULT NULL,
  `MaxEndurance` int(11) DEFAULT NULL,
  `Health` int(11) DEFAULT NULL,
  `Mana` int(11) DEFAULT NULL,
  `Endurance` int(11) DEFAULT NULL,
  `Concentration` int(11) DEFAULT NULL,
  `AccountName` varchar(255) NOT NULL,
  `AccountSlot` int(11) DEFAULT NULL,
  `CreationDate` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `LastPlayed` datetime DEFAULT NULL,
  `LastName` text,
  `GuildID` varchar(255) DEFAULT NULL,
  `Gender` int(11) NOT NULL,
  `Race` int(11) NOT NULL,
  `Level` int(11) NOT NULL,
  `Class` int(11) NOT NULL,
  `Realm` int(11) NOT NULL,
  `CreationModel` int(11) NOT NULL,
  `CurrentModel` int(11) NOT NULL,
  `Region` int(11) NOT NULL,
  `ActiveWeaponSlot` tinyint(3) unsigned NOT NULL,
  `Xpos` int(11) NOT NULL,
  `Ypos` int(11) NOT NULL,
  `Zpos` int(11) NOT NULL,
  `BindXpos` int(11) DEFAULT NULL,
  `BindYpos` int(11) DEFAULT NULL,
  `BindZpos` int(11) DEFAULT NULL,
  `BindRegion` int(11) DEFAULT NULL,
  `BindHeading` int(11) DEFAULT NULL,
  `BindHouseXpos` int(11) DEFAULT NULL,
  `BindHouseYpos` int(11) DEFAULT NULL,
  `BindHouseZpos` int(11) DEFAULT NULL,
  `BindHouseRegion` int(11) DEFAULT NULL,
  `BindHouseHeading` int(11) DEFAULT NULL,
  `DeathCount` tinyint(3) unsigned DEFAULT NULL,
  `ConLostAtDeath` int(11) DEFAULT NULL,
  `Direction` int(11) NOT NULL,
  `MaxSpeed` int(11) NOT NULL,
  `Copper` int(11) DEFAULT NULL,
  `Silver` int(11) DEFAULT NULL,
  `Gold` int(11) DEFAULT NULL,
  `Platinum` int(11) DEFAULT NULL,
  `Mithril` int(11) DEFAULT NULL,
  `SerializedCraftingSkills` text,
  `SerializedAbilities` text,
  `SerializedSpecs` text,
  `SerializedRealmAbilities` text,
  `DisabledSpells` text,
  `DisabledAbilities` text,
  `SerializedFriendsList` text,
  `SerializedIgnoreList` text,
  `IsCloakHoodUp` tinyint(1) DEFAULT NULL,
  `IsCloakInvisible` tinyint(1) NOT NULL,
  `IsHelmInvisible` tinyint(1) NOT NULL,
  `SpellQueue` tinyint(1) DEFAULT NULL,
  `IsLevelSecondStage` tinyint(1) DEFAULT NULL,
  `FlagClassName` tinyint(1) DEFAULT NULL,
  `Advisor` tinyint(1) DEFAULT NULL,
  `GuildRank` smallint(5) unsigned DEFAULT NULL,
  `PlayedTime` bigint(20) DEFAULT NULL,
  `DeathTime` bigint(20) DEFAULT NULL,
  `RespecAmountAllSkill` int(11) DEFAULT NULL,
  `RespecAmountSingleSkill` int(11) DEFAULT NULL,
  `RespecAmountRealmSkill` int(11) DEFAULT NULL,
  `RespecAmountDOL` int(11) DEFAULT NULL,
  `RespecAmountChampionSkill` int(11) DEFAULT NULL,
  `IsLevelRespecUsed` tinyint(1) DEFAULT NULL,
  `RespecBought` int(11) DEFAULT NULL,
  `SafetyFlag` tinyint(1) DEFAULT NULL,
  `CraftingPrimarySkill` int(11) DEFAULT NULL,
  `CancelStyle` tinyint(1) DEFAULT NULL,
  `IsAnonymous` tinyint(1) DEFAULT NULL,
  `CustomisationStep` tinyint(3) unsigned DEFAULT NULL,
  `EyeSize` tinyint(3) unsigned DEFAULT NULL,
  `LipSize` tinyint(3) unsigned DEFAULT NULL,
  `EyeColor` tinyint(3) unsigned DEFAULT NULL,
  `HairColor` tinyint(3) unsigned DEFAULT NULL,
  `FaceType` tinyint(3) unsigned DEFAULT NULL,
  `HairStyle` tinyint(3) unsigned DEFAULT NULL,
  `MoodType` tinyint(3) unsigned DEFAULT NULL,
  `UsedLevelCommand` tinyint(1) DEFAULT NULL,
  `CurrentTitleType` text,
  `KillsAlbionPlayers` int(11) DEFAULT NULL,
  `KillsMidgardPlayers` int(11) DEFAULT NULL,
  `KillsHiberniaPlayers` int(11) DEFAULT NULL,
  `KillsAlbionDeathBlows` int(11) DEFAULT NULL,
  `KillsMidgardDeathBlows` int(11) DEFAULT NULL,
  `KillsHiberniaDeathBlows` int(11) DEFAULT NULL,
  `KillsAlbionSolo` int(11) DEFAULT NULL,
  `KillsMidgardSolo` int(11) DEFAULT NULL,
  `KillsHiberniaSolo` int(11) DEFAULT NULL,
  `CapturedKeeps` int(11) DEFAULT NULL,
  `CapturedTowers` int(11) DEFAULT NULL,
  `CapturedRelics` int(11) DEFAULT NULL,
  `KillsDragon` int(11) DEFAULT NULL,
  `DeathsPvP` int(11) DEFAULT NULL,
  `KillsLegion` int(11) DEFAULT NULL,
  `KillsEpicBoss` int(11) DEFAULT NULL,
  `GainXP` tinyint(1) DEFAULT NULL,
  `GainRP` tinyint(1) DEFAULT NULL,
  `Autoloot` tinyint(1) DEFAULT NULL,
  `LastFreeLeveled` datetime DEFAULT NULL,
  `LastFreeLevel` int(11) DEFAULT NULL,
  `GuildNote` text,
  `ShowXFireInfo` tinyint(1) DEFAULT NULL,
  `NoHelp` tinyint(1) DEFAULT NULL,
  `ShowGuildLogins` tinyint(1) DEFAULT NULL,
  `Champion` tinyint(1) DEFAULT NULL,
  `ChampionLevel` int(11) DEFAULT NULL,
  `ChampionExperience` bigint(20) DEFAULT NULL,
  `ML` tinyint(3) unsigned NOT NULL,
  `MLExperience` bigint(20) NOT NULL,
  `MLLevel` int(11) NOT NULL,
  `MLGranted` tinyint(1) NOT NULL,
  `RPFlag` tinyint(1) DEFAULT NULL,
  `IgnoreStatistics` tinyint(1) DEFAULT NULL,
  `NotDisplayedInHerald` tinyint(3) unsigned DEFAULT NULL,
  `ActiveSaddleBags` tinyint(3) unsigned DEFAULT NULL,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `DOLCharactersBackup_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`DOLCharactersBackup_ID`),
  KEY `I_DOLCharactersBackup_Name` (`Name`),
  KEY `I_DOLCharactersBackup_AccountName` (`AccountName`),
  KEY `I_DOLCharactersBackup_GuildID` (`GuildID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
