CREATE TABLE IF NOT EXISTS `GuildRank` (
  `GuildID` varchar(255) DEFAULT NULL,
  `Title` text,
  `RankLevel` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `Alli` tinyint(1) NOT NULL DEFAULT '0',
  `Emblem` tinyint(1) NOT NULL DEFAULT '0',
  `Buff` tinyint(1) NOT NULL DEFAULT '0',
  `GcHear` tinyint(1) NOT NULL DEFAULT '0',
  `GcSpeak` tinyint(1) NOT NULL DEFAULT '0',
  `OcHear` tinyint(1) NOT NULL DEFAULT '0',
  `OcSpeak` tinyint(1) NOT NULL DEFAULT '0',
  `AcHear` tinyint(1) NOT NULL DEFAULT '0',
  `AcSpeak` tinyint(1) NOT NULL DEFAULT '0',
  `Invite` tinyint(1) NOT NULL DEFAULT '0',
  `Promote` tinyint(1) NOT NULL DEFAULT '0',
  `Remove` tinyint(1) NOT NULL DEFAULT '0',
  `View` tinyint(1) NOT NULL DEFAULT '0',
  `Claim` tinyint(1) NOT NULL DEFAULT '0',
  `Upgrade` tinyint(1) NOT NULL DEFAULT '0',
  `Release` tinyint(1) NOT NULL DEFAULT '0',
  `Dues` tinyint(1) NOT NULL DEFAULT '0',
  `Withdraw` tinyint(1) NOT NULL DEFAULT '0',
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `GuildRank_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`GuildRank_ID`),
  KEY `I_GuildRank_GuildID` (`GuildID`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
