CREATE TABLE `NpcTemplate` (
  `TemplateId` int(11) NOT NULL,
  `TranslationId` text,
  `Name` text NOT NULL,
  `Suffix` text,
  `ClassType` text NOT NULL,
  `GuildName` text,
  `ExamineArticle` text,
  `MessageArticle` text,
  `Model` text NOT NULL,
  `Gender` smallint(5) unsigned DEFAULT NULL,
  `Size` text NOT NULL,
  `Level` text NOT NULL,
  `MaxSpeed` smallint(6) NOT NULL,
  `EquipmentTemplateID` text,
  `ItemsListTemplateID` text,
  `Flags` smallint(5) unsigned DEFAULT NULL,
  `MeleeDamageType` tinyint(3) unsigned DEFAULT NULL,
  `ParryChance` tinyint(3) unsigned DEFAULT NULL,
  `EvadeChance` tinyint(3) unsigned DEFAULT NULL,
  `BlockChance` tinyint(3) unsigned DEFAULT NULL,
  `LeftHandSwingChance` tinyint(3) unsigned DEFAULT NULL,
  `Spells` text,
  `Styles` text,
  `Strength` int(11) DEFAULT NULL,
  `Constitution` int(11) DEFAULT NULL,
  `Dexterity` int(11) DEFAULT NULL,
  `Quickness` int(11) DEFAULT NULL,
  `Intelligence` int(11) DEFAULT NULL,
  `Piety` int(11) DEFAULT NULL,
  `Charisma` int(11) DEFAULT NULL,
  `Empathy` int(11) DEFAULT NULL,
  `Abilities` text,
  `AggroLevel` tinyint(3) unsigned DEFAULT NULL,
  `AggroRange` int(11) DEFAULT NULL,
  `Race` int(11) DEFAULT NULL,
  `BodyType` int(11) DEFAULT NULL,
  `MaxDistance` int(11) DEFAULT NULL,
  `TetherRange` int(11) DEFAULT NULL,
  `VisibleWeaponSlots` tinyint(3) unsigned NOT NULL,
  `ReplaceMobValues` tinyint(1) DEFAULT NULL,
  `PackageID` text,
  `LastTimeRowUpdated` datetime NOT NULL DEFAULT '2000-01-01 00:00:00',
  `NpcTemplate_ID` varchar(255) NOT NULL,
  PRIMARY KEY (`NpcTemplate_ID`),
  KEY `I_NpcTemplate_TemplateId` (`TemplateId`)
) ENGINE=InnoDB DEFAULT CHARSET utf8 COLLATE utf8_general_ci;
